### ISSUE TITLE
m.request broken for blob data in 2.0.4rc

### ISSUE THREAD

**Issue by CarlLeth** [MithrilJS/mithril.js#2392] opened 2019-03-08 18:36 UTC
### Mithril Version: 2.0.4rc

request.js, line 118, initializes the response to xhr.responseText before checking for an "extract" function. But the xhr.responseText getter throws an exception (in Chrome, at least) if the response type is anything other than '' or 'text', such as 'blob'. In 1.1.6, providing an extract function properly prevented mithril from calling the xhr.responseText getter.

## Steps to Reproduce
Submit 
```
var blobPromise = m.request({
    url: 'an endpoint returning file or blob data',
    config: xhr => xhr.responseType = 'blob',
    headers: { 'Accept': 'octet/stream' },
    extract: xhr => xhr.response
});
```

## Expected Behavior
The returned promise is fulfilled with the blob data.

## Current Behavior
Browser error: "Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob')."

## Possible Solution
Leave `response` uninitialized on line 118 of request.js. Set it to `xhr.responseText` before line 125 instead, and change line 123 to `response = args.deserialize(xhr.responseText)`.

## Environment
* Browser: Chrome 71.0.3578.80 (64-bit)

**Comment by isiahmeadows** [comment] 2019-03-08 23:30
Duplicate of #2333

**Closed by isiahmeadows** 2019-03-08 23:30 UTC
