### ISSUE TITLE
Routing with pathname reloads page in Chrome

### ISSUE THREAD

**Issue by jdemilledt** [MithrilJS/mithril.js#2176] opened 2018-06-06 12:40 UTC
## Expected Behavior
Mithril uses some JS API to change the URL shown in the omnibox without causing a reload whenever navigating to a different route

## Current Behavior
Page reloads the whole bundle on every route change

## Steps to Reproduce (for bugs)

https://gist.github.com/jdemilledt/251879795a3a9a04dcdf5a974ae77973

## Context
All of the benefits of having one bundle be downloaded are negated due to the webpage being reloaded on route changes

## Your Environment

* Version used: 1.1.6
* Browser Name and version: Chrome 66.0.3359.181
* Operating System and version (desktop or mobile): Arch Linux (no version, rolling release)
* Link to your project: Repository is private

**Comment by pygy** [comment] 2018-06-06 21:19
Hi @jdemilledt, from [this gist](https://gist.github.com/pygy/9e0435b4089f200820733507f8813451) you can see that the router works as intended. The code is live [here](https://bl.ocks.org/pygy/raw/9e0435b4089f200820733507f8813451), with the location bar being updated with no page reload.

You're probably not using the Polythene API as intended, I'll cc @ArthurClemens who'll be best placed to help you here.

**Comment by pygy** [comment] 2018-06-07 21:10
@jdemilledt I'm going to close this, @ArthurClemens [has found the source of the issue](https://gitter.im/ArthurClemens/Polythene?at=5b199991f4662f0f75acbfbb) and it is not a Mithril problem.

**Closed by pygy** 2018-06-07 21:10 UTC
