### ISSUE TITLE
Minor Feature: Normalize vnode.children passed to m() hypertext

### ISSUE THREAD

**Issue by ancmikesmullin** [MithrilJS/mithril.js#2526] opened 2019-09-05 16:06 UTC
**Mithril version:** 2.x

**Browser and OS:** FF Quantum Dev, Kali Linux

**Project:** Internal only

**Is this something you're interested in implementing yourself?** Did so in the form of a wrapper.

### Description

For all vnode children passed to `m()`:
- [ ] Recursively flatten any arrays given
- [ ] Drop any child which is `false`, `null`, or `undefined`

### Why

I needed this shim (see next section below) while updating Mithril 1.x => 2.x. 

I kept getting error `Vnodes must either always have keys or never have keys!`. The Changelog for `2.0.0` makes it sound like the above is already happening, but this was not my experience. In particular:

> hyperscript: when attributes have a null or undefined value, they are treated as if they were absent. #1773 (#2174)

> vnodes: normalize boolean children to null/undefined at the vnode level, always stringify non-object children that aren't holes (#2452 @isiahmeadows) Previously, true was equivalent to "true" and false was equivalent to "".

> This increases consistency with how booleans are handled with children, so it should be more intuitive.

There was a fourth case I ran into which is an invocation like:
```js
m('.a', m('.b', { key: 'X' }), [m('.c', { key: 'Y' }), ...]);
```
This was minorly frustrating because the children were all keyed but some were located in sub-arrays and needed flattening. It feels like core should be capable of doing these things. It simplifies the logic when you are building DOM trees using ternary operators, boolean operators, `_.map()`, etc.

### Possible Implementation

```js
const _m = window.m;
window.m = (a,b,...c) => {
    let args = [a];
    if (null != b && false !== b) {
        if (Array.isArray(b)) {
            const _b = _.flattenDeep(b);
            const list = [];
            for (const item of _b) {
                if (null != item && false !== item) {
                    list.push(item);
                }
            }
            if (list.length > 0) {
                args.push(...list);
            }
        }
        else {
            args.push(b);
        }
    }
    if (null != c && false !== c) {
        if (Array.isArray(c)) {
            const _c = _.flattenDeep(c);
            const list = [];
            for (const item of _c) {
                if (null != item && false !== item) {
                    list.push(item);
                }
            }
            if (list.length > 0) {
                args.push(...list);
            }
        }
        else {
            args.push(c);
        }
    }
    return _m(...args);
};
Object.assign(window.m, _m);
```

It would be nice if core did this by default.

### Open Questions

Would also be nice if that error provided some context about the tags around it. (ie. a list of strings)
```js
error.message += _.map(v.children, `${child.tag}.${child.attrs.class} key: ${child.key||child.attrs.key}`).join(', ');
```
I typically work with the minified version but was able to determine the cause by switching to source and inspecting the `for...loop` around the thrown `Error`.

You could argue that this is a waste of cycles for performance reasons and I might agree. Long-term I plan to design my Mithril components to handle their own normalization by just not generating non-normal markup, according to the new rules, but in this case I had to upgrade and I didn't have time to refactor.

**Comment by isiahmeadows** [comment] 2019-09-06 23:30
It's currently not well documented, only strongly hinted at in various places, but holes do serve a semantic purpose in unkeyed vnodes and aren't simply ignored internally like they were in v1 in keyed fragments. For instance:

```js
// Create both nodes to start
m.render(document.body, [
	m("div.foo"),
	m("div.bar"),
])

// The old `m("div.foo")` is removed, while the existing `m("div.bar")` remains
// because it's still there this render.
m.render(document.body, [
	null,
	m("div.bar"),
])

// The old `m("div.bar")` is removed and a new `m("div.bar")` added, because
// the new one isn't at the same array position as the old one.
m.render(document.body, [
	m("div.bar"),
	null,
])
```

I've got a note in #2528 to file a followup related to this. But in general, it's done this way because it's 1. just as easy to diff and 2. more predictable. The flattening behavior was removed in v1, but holes have been semantically significant for as long as I've been working on this project.

**Comment by ancmikesmullin** [comment] 2019-09-08 17:45
Ah, interesting. I had no idea! A doc chapter entitled "Holes" is probably relevant.

Maybe here: https://mithril.js.org/#dom-elements
or here: https://mithril.js.org/keys.html

an interesting quote from the Keys chapter:
> The problem is that from the point of view of the userList function, there's no way to tell if it was the first object that was removed, or if it was the second object that was removed in addition to the first object's properties being modified.

Its this sentence that tells me how keyed and non-keyed vnode diffing works. It just never thought far enough ahead to try to optimize the diffing by manually guaranteeing that the same object always resides at the same array index, where conditional siblings exist. An exaggerated example of that could be using sparse arrays in Javascript:

```js
const a = [,];
a[1]    = m('.b', 'b');
a[10]   = m('.c', 'c');
a[100]  = m('.d', 'd');
a[1000] = m('.e', 'e');
m('.a', a);
```

They take up no more memory than a normal array, but you have to iterate them correctly or you will waste a lot of cycles on the holes:
```js
 for (i in [,,,1,,,2,,,,3,,,,,,4]) { console.log(i); } // => 3,6,10,16
```

Honestly, though, you could still have this behavior if you implemented it with the `_.flattenDeep()` and `_.compact()` behavior in `m()`. In my mind, your idea of holes is a secondary system to the keys: system; you could call it the implicit key system, because you're still relying on keys, but the keys are the array index number. I would probably explain it that way, like a brief one-sentence, "If no key is specified, then the array index position is used instead." and maybe go on to differentiate why there is a rule that keys cannot be integers.

However, I would deprecate the idea of holes.

My initial takeaway from the document paragraph cited above was that if I didn't use `key:`s, then I had _no guarantee_ that my elements wouldn't redraw simply because their index position had changed. Not only is this behavior more intuitive (ie. it would require no change to documentation as stated), but it also enables the feature I want (the reason for opening this ticket).

Also, in my test of Mithril v1, this is the behavior I would frequently see. It was the cause of some "bugs" IMO. For example, In many cases I would try to apply CSS animations/transitions, or set "ontransitionend" event callbacks, but the Mithril redraw would interrupt them, causing the animation to restart, or the event be called inconsistently... and the redraw was only happening because of reordering, not because the element tag or attributes changed. I tried to work around this using tricks like `onbeforedraw() { return false; }` and by adding keys judiciously, even superstitiously... but it didn't totally fix the problem. I can confirm that Mithril v2 behaves as expected. Also, I have this normalization thing happening on top of v2 and its working for me without problems. I suppose in your view I am less performant because some redraws will happen due to reordering, and if I haven't keyed them, then this is causing unnecessary redraws.

But my counter-argument is again doubling-down on keys, if I didn't specify them, then I didn't care that they might be redrawn, or I knew that the list of sibling elements had no conditions and would remain constantly-ordered. This philosophy works for me. I just add keys when I recognize I have conditional siblings, or otherwise later on after I notice performance problems. If I wanted perfection, I would key everything--and this is very nearly where I am at today. To me, being explicit to achieve the performance gain is preferable to the quirky side-effects of having holes in the wrong places. If you keep the holes idea, you should definitely document the holes-in-wrong places side-effects as a warning against their accidental misuse, and emphasize that normalization _does not_ happen in `m()`. This potentially [but not for me because I have a normalization wrapper] adds a lot more boilerplate to user template code because they have to be extra careful to include holes where they should be, and omit them where they shouldn't be.

For example, in reference to your Incorrect vs. Correct holes example in #2528. The example provided is counter-intuitive to me. It seems anything that would modify the order of the output like `_.filter()` or `_.reduce()` cannot be used anywhere in the [Virtual] DOM tree. (Forgive the lodash version of these references.) Instead you would only use `_.map()`, and you would use it to replace non-matches with a `null`, thereby preserving the order of the elements around it in the case where their condition to render was false. It seems to me that your "Correct" example would produce an unpredictable ordering of elements based on which are "Active" at the time.

If we wanted to be really sneaky to try to meet in the middle, we could say that undefined keys are defined as the combination of their index offset PLUS [some scalar .toString() representation of the value] such as the `m()` tag/selector. ie. `0-p`, `1-.header`, `2-ul`, `3-li`, etc. This because selectors are already fairly unique in these scenarios for other reasons (to have a point to bind javascript, or to match css rules). Then the unoptimal redraw only occurs in a list of siblings with indistinguishable selectors. Some might argue that defining a unique selector is easier than defining a Mithril key attribute, and that it has more value for debugging and general semantics, as well. I've had many situations where the key value I assigned was basically a variation of or the same exactly as the selector, and other situations when debugging render problems where I wondered what the key was of a particular element in the devtools DOM Inspector view, so I ended up setting the key value as an attribute on the element within `view()` so it would be rendered on the element where I could see it.

My 2c, FWIW.

**Comment by ancmikesmullin** [comment] 2019-09-08 18:25
Ah, interesting. I had no idea! A doc chapter entitled "Holes" is probably relevant.

Maybe here: https://mithril.js.org/#dom-elements
or here: https://mithril.js.org/keys.html

an interesting quote from the Keys chapter:
> The problem is that from the point of view of the userList function, there's no way to tell if it was the first object that was removed, or if it was the second object that was removed in addition to the first object's properties being modified.

Its this sentence that tells me how keyed and non-keyed vnode diffing works. It just never thought far enough ahead to try to optimize the diffing by manually guaranteeing that the same object always resides at the same array index, where conditional siblings exist, without keying them. An exaggerated example of that could be using sparse arrays in Javascript:

```js
const a = [,];
a[1]    = m('.b', 'b');
a[10]   = m('.c', 'c');
a[100]  = m('.d', 'd');
a[1000] = m('.e', 'e');
m('.a', a);
```

They take up no more memory than a normal array, but you have to iterate them correctly or you will waste a lot of cycles on the holes:
```js
 for (i in [,,,1,,,2,,,,3,,,,,,4]) { console.log(i); } // => 3,6,10,16
```

Honestly, though, you could still have this behavior if you implemented it with the `_.flattenDeep()` and `_.compact()` behavior in `m()`. In my mind, your idea of holes is a secondary system to the keys: system; you could call it the implicit key system, because you're still relying on keys, but the keys are the array index position integer. I would probably explain it that way, like a brief one-sentence, "If no key is specified, then the array index position is used instead." and maybe go on to differentiate why there is a rule that keys cannot be integers.

However, I would deprecate the idea of holes.

My initial understanding from the document paragraph cited above was that if I didn't use `key:`s, then I had _no guarantee_ that my elements wouldn't redraw simply because their index position had changed. Not only is this behavior more intuitive (ie. it would require no change to documentation as stated), but it also enables the feature I want (and the reason for opening this ticket).

Also, in my test of Mithril v1, this is the behavior I would frequently see. It was the cause of some "bugs" IMO. For example, in many cases I would try to apply CSS animations/transitions, or set "ontransitionend" event callbacks, but the Mithril redraw would interrupt them, causing the animation to restart, or the event be called inconsistently... (this also happened with drag and drop interactions; the browser does not like when you remove/add the element during a drag...) and the redraw was only happening because of reordering, not because the element tag or attributes changed. I tried to work around this using tricks like `onbeforeupdate() { return false; }` and by adding keys judiciously, even superstitiously... but it didn't totally fix the problem. I can confirm that Mithril v2 behaves as expected, even with my normalization wrapper (read: without observing holes). I suppose in your view I am less performant because some redraws will happen due to reordering, and if I haven't keyed them, then this is causing unnecessary redraws.

But my counter-argument is again doubling-down on keys, if I didn't specify them, then I didn't care that they might be redrawn, or I knew that the list of sibling elements had no conditions and would remain constantly-ordered. This philosophy works for me. I just add keys when I recognize I have conditional siblings, or otherwise later on after I notice performance problems. If I wanted perfection, I would key everything--and this is very nearly where I am at today. (I actually have a render counter visibly integrated into my layout in dev.) To me, being explicit to achieve the performance gain is preferable to the quirky side-effects of having holes in the wrong places. If you keep the holes idea, you should definitely document a warning against their accidental misuse, and emphasize that normalization _does not_ happen in `m()`. This potentially [but not for me because I have a normalization wrapper] adds a lot more boilerplate to user template code because they have to be extra careful to include holes where they should be, and omit them where they shouldn't be.

For example, in reference to your Incorrect vs. Correct holes example in #2528. The example provided is counter-intuitive to me. It seems anything that would modify the order of the output like `_.filter()` or `_.reduce()` cannot be used anywhere in the [Virtual] DOM tree. (Forgive the lodash version of these references.) Instead you would only use `_.map()`, and you would use it to replace non-matches with a `null`, thereby preserving the order of the elements around it in the case where their condition to render was false. It seems to me that your "Correct" example would produce an unpredictable ordering of elements based on which are "Active" at the time.

Perhaps a clever middle solution is, we could say that undefined keys have a default value: _the combination of their index offset PLUS [some scalar .toString() representation of the value] such as the `m()` tag/selector_. ie. `0-p`, `1-.header`, `2-ul`, `3-li`, etc. This because selectors are already fairly unique in these scenarios for other reasons (to have a point to bind javascript, or to match css rules). Then the unoptimal redraw only occurs in a list of siblings with indistinguishable selectors. Some might argue that defining a unique selector is easier than defining a Mithril key attribute, and that it has more value for debugging and general semantics, as well. I've had many situations where the key value I assigned was basically a variation of--or the same exactly as--the selector, and other situations when debugging render problems where I wondered what the key was of a particular element in the devtools DOM Inspector view, so I ended up setting the key value as an attribute on the element within `view()` so it would be rendered on the element where I could see it.

My 2c, FWIW.

**Comment by isiahmeadows** [comment] 2019-09-09 05:56
@ancmikesmullin Long reply, but I'll try to address some of those points.

> Honestly, though, you could still have this behavior if you implemented it with the _.flattenDeep() and _.compact() behavior in m(). In my mind, your idea of holes is a secondary system to the keys: system; you could call it the implicit key system, because you're still relying on keys, but the keys are the array index position integer. I would probably explain it that way, like a brief one-sentence, "If no key is specified, then the array index position is used instead." and maybe go on to differentiate why there is a rule that keys cannot be integers.

Skipping holes is a *very* expensive operation to do, and matter of fact, that's why until recently `Array.prototype.forEach` was slower than this function with native arrays, by usually about 50-100% but sometimes as much as 3-4 times, depending on the circumstance:

```js
function forEach(array, func) {
	for (var i = 0, len = array.length; i < len; i++) {
		func(array[i], i, array)
	}
}
```

V8 in particular only started optimizing this once it was able to bail out mid-loop because of code like `[1, 2, 3].forEach((x, i, a) => { delete a[1]; console.log(x) })`, which is supposed to only log `1` and `3`. This is necessary because of how arrays are modeled internally: V8 literally has to change the array's internal representation because sparse arrays are modeled as int-to-pointer hash maps while dense arrays are implemented not unlike an `ArrayList` in Java. To explain what I mean, here's how each basic operation works underneath for dense arrays in a pseudo-JS syntax:

```js
// This is a simplified form of what most engines implement.
class DenseArray {
	#entries, #reserved, #length

	// Allocate
	constructor(reservedSize = 8) { // 8 is a common default
		// Round up to nearest power of 2, minimum 8. Uses a common bit hack.
		this.#reserved = reservedSize < 8 ? 8 :
			1 << (32 - Math.clz32(reservedSize - 1))
		this.#entries = c_malloc(this.#reserved) // Allocate memory
		if (this.#entries == c_nullptr) throw new Error("out of memory")
		this.#length = 0
	}

	// Length getter
	get length() { return this.#length; }
	// Setter omitted for expository purposes.

	// Not a real method, obviously.
	operator [](index) {
		return index < this.#length && index >= 0
			? load_pointer(this.#entries + index)
			: HOLE // Common sentinel used for non-existent properties.
	}

	// Push new entry
	push(entry) {
		// Make room if we have to
		if (this.#length == this.#reserved) {
			// Don't grow by too much
			let newLength = this.#reserved > 65536 /* 2^16 */
				? this.#reserved + 65536
				: this.#reserved << 1
			let entries = c_realloc( // Reallocate new pointer, copy memory
				this.#entries, newLength * sizeOfObjectInBytes
			)
			if (entries == c_nullptr) throw new Error("out of memory")
			// Store only if we know it's safe
			this.#entries = entries
			this.#reserved = newLength
		}

		// And now store it
		store_pointer(this.#entries + this.#length, entry);
		this.#length++
	}

	// Pop old entry
	public Object pop() {
		// Get the old entry
		let entry = load_pointer(this.#entries + this.#length - 1)
		this.#length--

		// Shrink if we've lost too much, but maintain the scale
		int minLength = this.#reserved > 65536 /* 2^16 */ * 2) {
			? this.#reserved - 65536
			: this.#reserved >> 1;
		if (minLength >= 8 && this._currentLength <= minLength) {
			let entries = c_realloc( // Reallocate new pointer, copy memory
				this.#entries, newLength * sizeOfObjectInBytes
			)
			if (entries == c_nullptr) throw new Error("out of memory")
			// Store only if we know it's safe
			this.#entries = entries
			this.#reserved = newLength
		}

		// And return the popped entry
		return entry
	}
}
```

Obviously, you can't just delete an entry with this model, and that's why they have to change their representation the moment you `delete` an entry from a dense array. But since you could do this in the middle of a loop, that's why they had to first find a way to bail out in the middle of an optimized loop (easier said than done) before they could optimize `Array.prototype.forEach` to compete with a `for` loop at all.

This performance issue was significant enough that the array iterators introduced in ES6/ES2015, like `Array.prototype.values`, explicitly *don't* skip holes in sparse arrays, breaking existing precedent. So if you did `for (const x of [1, 2, 3]) { delete a[1]; console.log(x) }`, it'd log `1`, `undefined`, and then `3`. It's only the last several months or so that V8 has had these optimizations in place, and other engines are only just now working on it.

> My initial understanding from the document paragraph cited above was that if I didn't use `key:`s, then I had no guarantee that my elements wouldn't redraw simply because their index position had changed. Not only is this behavior more intuitive (ie. it would require no change to documentation as stated), but it also enables the feature I want (and the reason for opening this ticket).

The issue isn't with not updating at all, but not updating the *correct* nodes. In general, you would usually experience degraded diff performance at worst, but this is not the case when transitions, animations, form inputs, and the like get involved. Any time the DOM or a child component has state independent of attributes that affect display or functionality, keys become essential to keep state correctly updated. Concretely, consider a comment listing, where you can reply to individual comments. This is where keys come in: if you have a comment text box open and then you add a new comment to the top of the list (say a new comment was submitted), you don't want the reply box to move up to the previous comment. But if you aren't using keys and you're storing the comment reply box's state within the component itself, the comment reply box *will* move up because Mithril doesn't know it needs to move the node and not just patch it.

> Perhaps a clever middle solution is, we could say that undefined keys have a default value:

I explicitly *won't* want this, because it's likely to generate more confusion than it addresses. Also, the iterative diff we do for unkeyed fragments (patch common indices, add newly added, remove newly removed) works like a keyed diff where each node has a `key` set to the vnode's array offset. Or in other words, the two fragments `[...vnodes]` and `[...vnodes].map((v, i) => m.fragment({key: i}, v))` render to the same DOM with the same state tracked. So your suggestion really isn't that far off of what we already do without keys. But still, the iterative diff is *different* enough that it's a bad idea to conflate the two.

> For example, in reference to your Incorrect vs. Correct holes example in #2528. The example provided is counter-intuitive to me. It seems anything that would modify the order of the output like `_.filter()` or `_.reduce()` cannot be used anywhere in the [Virtual] DOM tree. (Forgive the lodash version of these references.) Instead you would only use `_.map()`, and you would use it to replace non-matches with a `null`, thereby preserving the order of the elements around it in the case where their condition to render was false. It seems to me that your "Correct" example would produce an unpredictable ordering of elements based on which are "Active" at the time.

Keyed fragments are diffed by *key*, not by *offset*. Unkeyed fragments are diffed by *offset*, not by *key*. This is what makes them different. When you diff by key, it doesn't matter *where* the old value is, just what key it's associated with, because keyed fragments are like ordered maps. (This is also why it's called a *key*.) Unkeyed fragments are like ordered lists, so it *does* matter where the old value is - it's associated with the offset and not any externally-provided key.

**Comment by ancmikesmullin** [comment] 2019-09-09 18:56
I guess if I wanted to modify core I'd do it in here:
https://github.com/MithrilJS/mithril.js/blob/next/render/vnode.js#L6-L29
(Ironically the code I'm talking about is in the first 30 lines of the unminified release; I didn't even look)

line 8: `	if (node == null || typeof node === "boolean") return null`

So it seems like `null`/`undefined`/`false` are _already_ treated as `null`, which is half of my request here. Minus the part about removing them from the list, which _I realized actually don't care about whether they stay as "holes", or are removed_. So by keeping them, we satisfy your holes requirement.

The remaining work then is the array flattening, which can happen here:
```js
Vnode.normalizeChildren = function(input) {
	const children = [];
	let keyCount = 0;

	if (null == input || 'boolean' === typeof input) {
		children.push(null);
	}
	else if ('number' === typeof input) {
		children.push(String(input));
	}
	else if ('string' === typeof input) {
		children.push(input);
	}
	else if ('object' === typeof input && null != input.tag) { // instanceof Vnode
		children.push(input);
		if (input.key) keyCount++;
	}
	else if (Array.isArray(input) && input.length < 1) {}
	else if ('function' === typeof input[Symbol.iterator]) { // ie. Array, Object, Set, Map, etc.
		for (const v of input) {
			for (const vv of Vnode.normalizeChildren(v)) {
				children.push(Vnode.normalize(vv));
				if (input.key) keyCount++;
			}
		}
	}
	if (keyCount > 0 && keyCount !== children.length) {
		throw new TypeError("Vnodes must either always have keys or never have keys!")
	}
	return children;
}
```

Tested and works for me locally. It allows me to remove the component wrapper.

Points of caution:
- Using ES6 `const` and `let` keywords. Is that naughty?
- I wasn't sure about the array optimization stuff. I'd be curious how the microbenchmark says my specialized switch performs versus the "*very* perf-sensitive check" that was there before.
- Added coverage for non-Array [ES6] Iterables.
- Assuming a Vnode is any Object with a .tag attribute. Could maybe have said `'string' === typeof input.tag` to be more specific. But actually would prefer if I could use `input instanceof Vnode` or similar. Didn't take it that far.

As far as documentation of holes, maybe it could go something like this:

So holes vs. keys only apply:
1) When you have more than one child on the same level (siblings, in a list)
ie. `m('tag', {}, [...])`

In these cases, the concern is primarily their position in the list, because this is how the Virtual DOM diff engine works. It looks at the position in VDOM vs. DOM, and if the element at index N is !== on both sides, then DOM manipulation must occur.

You have three choices:  
a) **Don't worry about it.**  
    A fine option when the list element order and length are constant/non-conditional.
b) **Holes**: Use `null` as a placeholder where elements may conditionally pop in/out of existence.  
   The idea being to preserve the order and length of the list for remaining elements.
   This way you guarantee only one DOM manipulation is necessary, instead of one for the removed element, and one for all remaining elements which must have their position in the tree reordered.
c) **Keys**: Specify a unique id in the `{ key: string }` attribute (unique among the list of siblings). (Since Mithril v2, if you specify a key for one sibling, you must also specify a key for all remaining siblings, or an error will occur at render time.)  
    A list of keyed siblings are more like an `Object.assign()`. Only keys added/removed since last render require DOM manipulation, and the rest are ignored/unchanged.

NOTICE: `null`/`undefined`/`false` child values are converted to `null`, but otherwise retain their position in the array, as an optimization, so sibling offsets remain constant and do not require array resizing or DOM reordering.

NOTICE: Any iterables used within the `m(tag, attrs, ...children)` fn's `children` attribute will be flattened, such that `m('a', 'b') === m('a', ['b']) === m('a', [[[['b']]]])`. 

I don't see the array flattening as threatening to the holes because the effective offset remains the same after flattening.

**Comment by ancmikesmullin** [comment] 2019-09-09 19:23
Ah, but there is an issue where I am mixing keys and nulls, if I choose not to remove them. 

How much work would it be to change keyed-diff to just ignore nulls? Seems like a simple change but it would have to be repeated for each of the strategies. Not sure if there are other ramifications.

```js
				// keyed diff
				var oldEnd = old.length - 1, end = vnodes.length - 1, map, o, v, oe, ve, topSibling
				// bottom-up
				while (oldEnd >= oldStart && end >= start) {
					oe = old[oldEnd]
					ve = vnodes[end]
					if (!(null == oe && null == ve)) {
						if (oe.key !== ve.key) break
						if (oe !== ve) updateNode(parent, oe, ve, hooks, nextSibling, ns)
						if (ve.dom != null) nextSibling = ve.dom
					}
					oldEnd--, end--
				}
```

**Comment by isiahmeadows** [comment] 2019-09-09 20:16
I do want to point out one other case where flattening is bad. Consider this component:

```js
var Layout = {
	view: function (vnode) {
		return m("div.body", [
			m("header", m("h2", vnode.attrs.header)),
			vnode.children,
			m("footer", m(Copyright)),
			m(HelpModal),
		])
	}
}

function HelpModal() {
	var show = true // Click the "X" to hide it
	return {view: function () { /* omitted */ }}
}
```

Now, suppose you conditionally added a couple nodes:

```js
m(Layout, {header: "My beautiful route"}, [
	m("div", "stuff"),
	showInfo && [
		m("div.date", date.toLocaleDateString("en-US", {
			year: "numeric",
			month: "long",
			day: "numeric",
		})),
		m("div.file-size", fileSize),
	],
])
```

Looks completely innocuous, but this relies on non-flattening behavior to work. When `Layout` renders, it renders to this tree:

```js
m("div.body", [
	m("header", m("h2", vnode.attrs.header)),
	[
		m("div", "stuff"),
		showInfo ? [
			m("div.date", date.toLocaleDateString("en-US", {
				year: "numeric",
				month: "long",
				day: "numeric",
			})),
			m("div.file-size", fileSize),
		] : null,
	],
	m("footer", m(Copyright)),
	m(HelpModal), // This is a stateful component
])
```

If you flatten it, it ends up rendering to this:

```js
m("div.body", showInfo
	? [
		m("header", m("h2", vnode.attrs.header)),
		m("div", "stuff"),
		m("div.date", date.toLocaleDateString("en-US", { /* omitted */ })),
		m("div.file-size", fileSize),
		m("footer", m(Copyright)),
		m(HelpModal),
	]
	: [
		m("header", m("h2", vnode.attrs.header)),
		m("div", "stuff"),
		false,
		m("footer", m(Copyright)),
		m(HelpModal),
	]
)
```

Suppose the user closes the help modal, and later, during normal use of the application, `showInfo` changes from `true` to `false`. If you look at the offset of the stateful `m(HelpModal)`, you'll notice it changed. Previously, it was the 6th entry, and now it's the 5th. Here's how Mithril diffs that change:

1. Patch: `m("header", ...)` &rarr; `m("header", ...)`
1. Patch: `m("div", ...)` &rarr; `m("div", ...)`
1. Add: `null` &rarr; `m("div.date", ...)`
1. Replace: `m("footer", ...)` &rarr; `m("div.date", ...)`
1. Replace: `m(HelpModal)` &rarr; `m("footer", ...)`
1. Add: (none) &rarr; `m(HelpModal)`

The previous instance is torn down completely in step 5, and the new instance is set up in step 6. Since the modal appears on load without any consultation with global state, it used to be closed and now it reappears, surprising the user and developer both. It's not obvious, but it's because `vnode.children` is just an array - it's not set to a reified fragment with `tag: "{"` and everything.

This is the main reason why I'm highly skeptical on flattening children: it leads to very counterintuitive behavior in circumstances where one would reasonably expect it would otherwise work. (I wouldn't consider auto-flattening a minor feature, and this is why.)

**Comment by ancmikesmullin** [comment] 2019-09-09 20:40
But flattening is independent of holes;
with or without flattening:
- If the siblings are keyed, this is not an issue.
- If the siblings aren't keyed, you would have to make holes:
`!showInfo ? [,,] : [ m('div.date', ...), m('div.file-size', ...) ]`
to avoid reorder rendering.

**Comment by isiahmeadows** [comment] 2019-09-09 21:15
Keying at that scale is *not* something I'd like to add, and I'd also like to avoid requiring other various hacks for things common enough they *should* be simple and intuitive.

This was also discussed a while back on Gitter and other channels with other core contributors in the past as I looked into it personally for potential performance improvements, and the benefits of flattening just don't seem apparent to any of us. If anything, flattening creates more problems than it solves, and it's also noticeably slower to process. If you really want explicit flattening and spreading, it's not that hard to just do `...array.map(whatever)` or similar as a child, and you can do this even in JSX via `{...array.map(whatever)}`. (This is, of course, meaningless in React, but other frameworks require this, too.)

Closing, because this is not going to happen without something much more compelling than this.

**Closed by isiahmeadows** 2019-09-09 21:15 UTC
Labels: Type: Breaking Change, Type: Enhancement
