### ISSUE TITLE
Unmounting a component keeps reference to root DOM Element

### ISSUE THREAD

**Issue by gregdking** [MithrilJS/mithril.js#727] opened 2015-07-22 13:17 UTC
I am using Mithril to generate pages and reusable components inside of a larger SPA framework (which it works awesome for by the way). When I unload any pages that use Mithril, I am calling:

``` JavaScript
m.mount(rootElement, null);
```

as documented. This successfully unloads the controller and the virtual DOM object. However it it still leaves a reference to the rootElement DOM object.

I did a heap snapshot:

![image](https://cloud.githubusercontent.com/assets/4176571/8825487/78063bfa-304d-11e5-8d7f-c86ad7625e7e.png)

The `HTMLDivElement` highlighted in red is the rootElement I passed into `m.mount()`. The red highlight indicates that it has been detached from the DOM, but its presence in the heap snapshot indicates that there is still a JavaScript reference pointed to it.

The line where I added the arrow shows that the reference is in the `roots` array within Mithril. Sure enough, looking in the code I can see where the correct entries in the `controllers` and `components` arrays get null-ed out. However, it does not look like the entry in `roots` ever does.

In addition, it looks like the `roots`, `controllers`, and `components` arrays will forever increase in size with the `controllers` and `components` arrays getting holes where controller and component have been set to null. I would think over time that this would degrade performance.

I propose that if we unmount a DOM element by passing null to `m.mount()` that the reference to the DOM element be removed in addition to removing the controller and component. I also suggest that the entries be deleted from their respective arrays to keep the arrays compact.

If there are issues with putting this behavior directly into `m.mount()`, I would also be happy with another method specifically for removing the reference to rootElement when I know for a fact that it is about to get removed from the DOM.

**Comment by impinball** [comment] 2015-07-23 11:59
Sounds like a memory leak to me. Granted, there are other known problems with this library from an architectural standpoint. Can you find a minimal case where the reference is still kept?

**Comment by impinball** [comment] 2015-07-23 12:00
And as for the rest, PRs are always welcome.

**Comment by lhorie** [comment] 2015-07-24 02:12
This is fixed in origin/next

**Comment by ketan** [comment] 2016-09-01 17:11
I'd like to point out that this bug has re-surfaced.

The root cause is that [this code](https://github.com/lhorie/mithril.js/blob/0159cd667ad85cd82d92fcb31a33f75be6539f6d/mithril.js#L1461-L1463), which is supposed to remove the reference to the DOM node when `component` is `null`, is never executed, because of [this line](https://github.com/lhorie/mithril.js/blob/0159cd667ad85cd82d92fcb31a33f75be6539f6d/mithril.js#L1447) which always initializes a `component` to `{controller: noop}`.

**Comment by pygy** [comment] 2016-09-01 18:49
@ketan Thanks for the detailed report. Follow up: #1289

**Comment by isiahmeadows** [comment] 2016-11-23 06:21
Reopening, since there's an outstanding fix in #1321.

**Comment by dwaltrip** [comment] 2017-04-27 23:56
Is there a simple fix for this memory leak? I looked at the pull request (which was never merged), and the changes to the main `mithril.js` module look non-trivial.

I'm fine with forking v0.2.5 myself and adding the change.

Here is a fairly minimal test case: https://gist.github.com/dwaltrip/f77e7e4272d407f04311efd0e7d48457

I used Chrome heap snapshot to verify the memory leak. This memory leak doesn't occur if this code is upgraded to mithril `v1.1.1`.

**Comment by dwaltrip** [comment] 2017-04-28 03:46
So, guided by Ketan's clues, I took a closer look at @pygy 's pull request (#1321). The part related to the memory leak is actually super simple, at least as far as I could tell. I was able to make a branch that fixes the leak! I verified this using the test case described in my previous comment.

Here are the changes I made: https://github.com/lhorie/mithril.js/compare/v0_2_x...dwaltrip:spike/fix-mount-memory-leak

All the tests still pass... so I'm guessing everything else still works. I'm going to give this branch a shot and see if it does the trick for me. Perhaps this can be turned into a PR as well, if there is any interest.

**Comment by ketan** [comment] 2017-04-28 03:53
> So, guided by Ketan's clues, I took a closer look at @pygy 's pull request (#1321). The part related to the memory leak is actually super simple, at least as far as I could tell. I was able to make a branch that fixes the leak! I verified this using the test case described in my previous comment.

Here's the patch we'd applied on mithril 0.2.5 — https://github.com/gocd/gocd/pull/2694. It was based off a PR someone had submitted to this repository, can't seem to find it anymore.

**Comment by dwaltrip** [comment] 2017-04-28 04:01
Awesome, that fix looks very similar. Good to know it's working for your team.

**Comment by isiahmeadows** [comment] 2017-04-28 06:00
@ketan Could you file a PR against `v0_2_x`, so we can patch that bundle separately?

**Comment by tivac** [comment] 2017-04-28 06:55
This is unimportant, but we should rename that branch to `legacy` or something. That branch name is crazy ugly.

**Comment by isiahmeadows** [comment] 2017-07-13 00:51
Closing - last v0.2 release has been cut.

**Closed by isiahmeadows** 2017-07-13 00:51 UTC
Labels: 0.2.x, bug
