### ISSUE TITLE
Add ES module export version

### ISSUE THREAD

**Issue by porsager** [MithrilJS/mithril.js#2112] opened 2018-03-29 22:30 UTC
Until/if Mithril switches to ES modules, and eg. rollup, it would be nice to have an ES module bundle for mithril and mithril/stream.

My suggestion is a simple addition in the form of a new bundle, based on the current one, but changed to use `export default m` and `export { stream }` instead and then add `"module": "mithril.mjs"` to package.json

I've just finished support for ES modules in flems (not deployed to main yet), and thought it would be great to be able to do
```
import m, { stream } from 'mithril'
```

[Here is a flems example using bss](https://next.flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4IWAA60ATsQAEAIzlhptLHIDkCuHA0AdNAYX5qOgBTADcxbQAmAT0SL8C6mY0BlRjCgAhKACuMBoAlAasIZQgcD4w1MQQ9Ag8ACyIAExsHCCYOHgmOlFCjMw8bAC6rEA)

Would a pull request for this be welcomed?

**Comment by futurist** [comment] 2018-07-21 08:29
+1 for this, very needed for a modern application.
Any response? @lhorie  @pygy @tivac @barneycarroll

**Comment by barneycarroll** [comment] 2018-07-21 08:35
I would love to see that PR!

**Comment by isiahmeadows** [comment] 2018-11-13 23:34
Duplicate of #1886

**Closed by isiahmeadows** 2018-11-13 23:34 UTC
Labels: enhancement

**Comment by isiahmeadows** [comment] 2018-11-14 00:40
Just found the dupe...sorry!
