### ISSUE TITLE
m.render inside route onmatch causes infinite loop

### ISSUE THREAD

**Issue by BobbyGerace** [MithrilJS/mithril.js#2490] opened 2019-07-26 14:24 UTC
In the code below, the onmatch function is called over and over again in a loop, and the `Component` is never actually rendered. I'm new to Mithril so I may just be doing something wrong, but I didn't see anything in the documentation indicating that I shouldn't do this.

``` js
const Component = {
    view: function() {
        return m('div', 'hello world')
    }
};

m.route(document.body, '/index', {
    '/index': {
        onmatch: function() {
            console.log('onmatch was called');

            // Show loading while we load data
            m.render(document.body, m('div', 'loading...'));

            return new Promise(function(resolve, reject) {
                setTimeout(resolve, 1000);
            }).then(function() {
                return Component;
            });
        }
    }
})
```

The issue seems to be with the call to m.render. If you comment that out it works fine.

**Comment by osban** [comment] 2019-07-26 14:33
@SleepyPierre if you choose a different mount point to render the loading div, it'll work.
E.g.: `<div id=test></div>`
And then: `m.render(document.getElementById('test'), m('div', 'loading...'));`

**Comment by SleepyPierre** [comment] 2019-07-26 15:16
@osban That does work, but what I really want is for the loading div to replace the content of the current route while the next route loads. And the only way I can see to do that is if the mount point of the loading div is the same as the mount point of the routes.

If I just change the mount point of the loading div, then the loading would appear next to the content, and it does not go away once the route's content has loaded.

Obviously this is a contrived example and there is only one route, but I think you can see what I'm getting at.

**Comment by osban** [comment] 2019-07-26 15:25
@SleepyPierre I think in that case it's easier to deal with it in the components, something like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIstACYwokgLyTgAHTSTJsjMQyJJyALobWGjeKkAZWhlkQ0Ac2WqAbhBgB3AwAoAlMoAfNI+AOSEAIyhFJJqIDZ2Do74KXF+ZmgW9BKSALIYDi7qmpL0DhDEvgFKwcVaWgD0DZJgMMTUhNq6GJKEMABOMBpa7MOS7l5VQYZjWgCEMvJQ+Dp6+LBOxJ2zkgD8IQn2Tn47Blhh9q7RsSAAKn2SaLT9WBiKAA4YjkMgJyUmaAyGiw+BkAFcGD5ZLRqGCcAx8AAjOQATxi+QcfkoIDgChg1GIEGyeAiADZEAAGNgcECYHB4fDUOACGj0RjMHhsIxUKAOADWCBQnHpPCwFUI-Wg2LB-XIPBIxHecEQTQh7z5yToWAaYq2kqgAAEIvhjaSdeL9fh+NjiCj3twcdRJe9RKwjKwgA).

**Comment by SleepyPierre** [comment] 2019-07-26 15:54
That worked, thanks!

I'll still leave this issue open, as I still believe it's a bug. (This worked in an older version, so I'm sure more people will come across this as they upgrade)

At the very least, there should probably be an error message and/or a note in the change log

**Comment by isiahmeadows** [comment] 2019-07-26 22:50
@SleepyPierre Your component should handle the temporary loading, not the `onmatch`. Think of it in terms of states. Something like this should work better:

```js
// Make sense of the loading, so you can actually do stuff with it.
// And yes, I've been considering making this a core component:
// https://github.com/MithrilJS/mithril.js/issues/2282
function Async({attrs: {load}}) {
	let state = "pending", result
	new Promise(resolve => resolve(load())).then(
		v => { state = "ready"; result = v },
		e => { state = "error"; result = e }
	)
	return {
		view: function ({attrs: {pending, ready, error}) {
			if (state === "pending") return pending()
			if (state === "ready") return ready(result)
			if (state === "error") return error(result)
		}
	}
}

const Component = {
    view: function() {
        return m('div', 'hello world')
    }
};

m.route(document.body, '/index', {
    '/index': {
		render: () => m(Async, {
			async load() {
				await new Promise(resolve => setTimeout(resolve, 1000))
				return Component
            },
			ready: Component => m(Component),
			error: e => m("div", ["Whoops! ", e.message]),
        }),
    }
})
```

The infinite loop sounds like a bug, though. It should be stepping on `m.mount`'s toes behind the scenes, not generating infinite loops. (`m.mount` should really be throwing if attempting to mount to a DOM node with a non-empty vnode tree.)

**Comment by dead-claudia** [comment] 2024-09-02 19:14
Closing due to age.

**Closed** 2024-09-02 19:14 UTC
Labels: Type: Bug, Area: Core

**Comment by kfule** [comment] 2025-06-15 03:48
FYI 
The infinite loop bug is reproduced in v2.0.4, but not in v2.2.0 or later versions.
[flems v2.0.4 (reproduced)](https://flems.io/mithril@2.0.4#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgGFKsAHa+tgLytgAHTSsJrAG4QYAd0SswAVzTkaEagAoAlMLGTDrAE4way4+KxaA5ABMIUmyVY2AFjChRKrOZWNQdjY6BpIAvmJhANxiYlj4xpTKdFp2lOTKOLT4AEaUdgCeLjYA9BBodjAAHs764pKl5ZU1iqL1RqzUWBg05G6KKmoa2nptHR1McJSw+N4A5rZdPX2+GHCs5BheMEE6MWih45IlJawAym6UcqzeGA5oc75u0DC+r7d2rHY9GIdHrPFTBUYMZUulMvxcvkigDbA4nMUPuU5vhUcE9rF2v9TOZLKw0PJWAAFRJYCBwGBaQbqTRoLSmKZQKQwFymQgwdSjP7-SQUmgAFQgOCSNHp8GmzJcAEYAAxyjFYo5hHT4GgeOnU4Z0rmKnkmMwWcScHh8Wj7PWsZXm8YRLG25UgMgU2A06gIRAgABMUsQnpAYQAumEgA)
[flems v2.2.0 (not reproduced)](https://flems.io/mithril@2.2.0#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgGFKsAHa+tgLytgAHTSsJrAG4QYAd0SswAVzTkaEagAoAlMLGTDrAE4way4+KxaA5ABMIUmyVY2AFjChRKrOZWNQdjY6BpIAvmJhANxiYlj4xpTKdFp2lOTKOLT4AEaUdgCeLjYA9BBodjAAHs764pKl5ZU1iqL1RqzUWBg05G6KKmoa2nptHR1McJSw+N4A5rZdPX2+GHCs5BheMEE6MWih45IlJawAym6UcqzeGA5oc75u0DC+r7d2rHY9GIdHrPFTBUYMZUulMvxcvkigDbA4nMUPuU5vhUcE9rF2v9TOZLKw0PJWAAFRJYCBwGBaQbqTRoLSmKZQKQwFymQgwdSjP7-SQUmgAFQgOCSNHp8GmzJcAEYAAxyjFYo5hHT4GgeOnU4Z0rmKnkmMwWcScHh8Wj7PWsZXm8YRLG25UgMgU2A06gIRAgABMUsQnpAYQAumEgA)
[flems latest version (not reproduced)](https://flems.io/mithril#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgCsEAaEAYwHs0AXGWvKtOGgAgGFKsAHa+tgLytgAHTSsJrAG4QYAd0SswAVzTkaEagAoAlMLGTDrAE4way4+KxaA5ABMIUmyVY2AFjChRKrOZWNQdjY6BpIAvmJhANxiYlj4xpTKdFp2lOTKOLT4AEaUdgCeLjYA9BBodjAAHs764pKl5ZU1iqL1RqzUWBg05G6KKmoa2nptHR1McJSw+N4A5rZdPX2+GHCs5BheMEE6MWih45IlJawAym6UcqzeGA5oc75u0DC+r7d2rHY9GIdHrPFTBUYMZUulMvxcvkigDbA4nMUPuU5vhUcE9rF2v9TOZLKw0PJWAAFRJYCBwGBaQbqTRoLSmKZQKQwFymQgwdSjP7-SQUmgAFQgOCSNHp8GmzJcAEYAAxyjFYo5hHT4GgeOnU4Z0rmKnkmMwWcScHh8Wj7PWsZXm8YRLG25UgMgU2A06gIRAgABMUsQnpAYQAumEgA)

It seemed to be caused by `oncreate` in the RouterRoot component calling `resolveRoute` and the RouterRoot component being deleted once by `m.render` (and re-created by m.redraw).
https://github.com/MithrilJS/mithril.js/blob/caef6a8f096c41e2fab732c21e436d8ab9c1023f/api/router.js#L165
In v2.2.0, `oncreate` has been removed and it seems that an infinite loop no longer occurs when drawing with `m.render` in `onmatch`.

I am interested in the example of the "loading..." use case with `onmatch` and found this issue page.
