### ISSUE TITLE
REM is down. Tutorial is broken.

### ISSUE THREAD

**Issue by Apromixately** [MithrilJS/mithril.js#2595] opened 2020-05-13 14:03 UTC
EOM

**Comment by isiahmeadows** [comment] 2020-05-17 23:50
Can't reproduce it personally - might be a regional issue. In either case, it's not an issue with Mithril (and I noticed lhorie/rem#9 was similarly filed by you), so I'm closing.

**Closed by isiahmeadows** 2020-05-17 23:50 UTC
Labels: Type: Bug
