### ISSUE TITLE
Error: You gave us a visitor for the node type "JSXFragment" but it's not a valid type

### ISSUE THREAD

**Issue by venom90** [MithrilJS/mithril.js#2590] opened 2020-05-01 07:57 UTC
**Mithril version:2.0.4**

**Node Version:12.16.2**

**Browser and OS:Chrome**

## Code

index.js
```javascript
import m from 'mithril';

function App() {
  return {
    view: () => <div>Hello, world</div>,
  };
}

m.mount(document.body, App);
```

webpack.config.js
```javascript
const path = require('path')

module.exports = {
    entry: './src/index.js',
    output: {
        path: path.resolve(__dirname, './bin'),
        filename: 'app.js',
    },
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /\/node_modules\//,
            use: {
                loader: 'babel-loader'
            }
        }]
    }
}
```
.babelrc
```javascript
{
    "presets": ["@babel/preset-env"],
    "plugins": [
        ["@babel/plugin-transform-react-jsx", {
            "pragma": "m",
            "pragmaFrag": "'['"
        }]
    ]
}
```

package.json
```javascript
{
  "name": "learn-mithril",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack -d --watch"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mithril": "^2.0.4"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.6",
    "@babel/plugin-transform-react-jsx": "^7.9.4",
    "@babel/preset-env": "^7.9.6",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  }
}

```

## Expected Behavior

- JSX should render

## Current Behavior
- Getting following error

```javascript
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: You gave us a visitor for the node type "JSXFragment" but it's not a valid type
    at verify (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-traverse/lib/visitors.js:196:13)
    at Function.explode (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-traverse/lib/visitors.js:72:3)
    at Plugin.normaliseVisitor (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/plugin.js:155:29)
    at new Plugin (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/plugin.js:66:27)
    at Function.memoisePluginContainer (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/file/options/option-manager.js:119:21)
    at Function.normalisePlugin (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/tirumalrao/Learning/learn-mithril/node_modules/babel-loader/lib/index.js:173:20)
```

**Comment by isiahmeadows** [comment] 2020-05-18 03:28
Remove `babel-core`, and you should be good. Babel 7.0 is what added support for JSX fragments, and [this](https://babeljs.io/setup) recommends you only install `@babel/core`, not also the older `babel-core`. [The website doesn't recommend installing both, either.](https://mithril.js.org/jsx.html#using-babel-with-webpack)

Closing as it's not a bug in Mithril or its docs.

**Closed by isiahmeadows** 2020-05-18 03:28 UTC
Labels: Type: Question
