### ISSUE TITLE
Unexpected form behavior onblur

### ISSUE THREAD

**Issue by pereriksson** [MithrilJS/mithril.js#2638] opened 2020-11-06 18:08 UTC
**Mithril version:** 2.0.4

**Browser and OS:** Version 86.0.4240.183 (Official Build) (x86_64) on Mac OS X 10.15.6

**Project:** A simple app to administer rooms for a piece of real estate.

When the user leaves an input field in our app, its value is directly sent to the backend (onblur). This is to increase the user experience.
The example code has been simplified (62 lines of code) to ease troubleshooting.

The issue can be produced with the code at: https://flems.io/#0=N4IgtglgJlA2CmIBcB2AjAOgEwGYA0IAZhAgM7IDaoAdgIZiJIgYAWALmLCAQMYD21NvEHIQAHigQAbgAJoAXgA6IAE58+YUsoB8YgPSSp27iFLwEPNhAHkmABiRYsIAL54a9RswBW5XgKERJmUAVzMZUjYVCEtlAG5FakSENhkAJXUwAFk+KHMZeRlgRJlSiNopeAB9YnMoJBlCEOpLa2oACgBKIpKysr09GQBlYSgZWhkVeABHEPhImTY+RZZ4GQAjWh4Aa1HF5ZCAByhaIRW1gHNpYUnMjHve0rdEx5kL+DYqtQ1SBqaWqwCLo9ah9PoDGQAQVB8AAHvRDghJvNDjY1oQ1GANltdtQoPcMK8+hkNDk8rAMN9NAUZFRlNBlEhlOg0ABWACcyjwyjoDEZPM8XOUeVIPGih0BSWQwvmYogErayhcAF0EqCys9qC41Yl-q0BOlMqRgcV1aUpmwQipQaawWUBBBqBA2H9mvqOt1bXawSTsrlzBh3p8qcbOmrvTJNRGpBB4AB3V0Atomonei1W0FgdoAckM2bwtNTEdKWezLCw+Zk2d9pGznW5ZuLfVLbFo6wQlYoRabZV9ZIDIYwYFoh3aesl7SktFgc093Z7YPT1sLjYXC5bKk787XTZbUEr2YAcp46w2d+eynv89uL03gFHb4+u6vH7fS47DiE2NeX6-X16-0AsE2AAT0OeAGmUIRYTYIVfyA18BHbK0Gj7f0KVICpqlqWAoDPBCCKnGcIJkIi5gwXl4HwgjHxcTobxo5UGL-etmPPZVWPgv8Ny3LiaJLHM2H3AtswAEVlcVJVPNigKvAtn34ncWzhVsploH9FNvADNNvJCZxUVDMn7DCsJqWNcOonSFwfKyFzI+AMBFOUFQEGSaPovj+I4tyLyYzzbw8gjVR8jVAvYsKmw48NvRcV5Yq1F4nUIGR2igPgeBCBhBEDD4AFEECytgACEQIASSgHMQzrGQAEJCmoEJYFgOdGzAIc+GaNhUvSzLhDYHK2Hy+BCpK8rKqNU9DR+MNEnikwzAsSVbBAVksCQNAAA5XHcEBKNEDAeFIPwQH4QQ+tEVxlQIWBHW2WwqF2zxREgNgWGiLgCCtLgmHYNhDl+AZmkObYLgOjQ9Bet6SAAASwDA7AwAAWCHnShilIGoDBfBMUDwNEUVJMulwgA

## Steps to Reproduce
1. Click on the first form element to give it focus.
2. Click on the second form element to give it focus.

## Expected Behavior
Focus is set on the second input element and its contents is not lost.

## Current Behavior
Focus is set on the second input element and its contents _is_ lost.

## Context
This is causing data loss for the user in our front end application where customers administer their information.

We are greatful for any help!
Per

**Comment by pereriksson** [comment] 2020-11-06 18:17
The bug seems to disappear if the textarea is changed to an input[type="text"] instead.

**Comment by isiahmeadows** [comment] 2020-11-08 00:29
Confirmed, though the reason is indirect. Basically, we remap the children to `value` instead of `defaultValue` (what we should be doing).

To work around this short term, move your `value.description` child to a `defaultValue` attribute of `textarea` - [MDN explains it well enough in its docs for the textarea DOM element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement).

**Comment by shekharsom** [comment] 2020-11-08 17:00
I didn't understand the error.

The savefield action should be updating the state and then should save the data in the backend. There is no two way binding of properties in mithril IMHO
Input & TextArea take value as a parameter and not as innertext. So, the value shouldn't be entered as third parameter but as value only.

[example](https://flems.io/#0=N4IgtglgJlA2CmIBcB2AjAOgEwGYA0IAZhAgM7IDaoAdgIZiJIgYAWALmLCAQMYD21NvEHIQAHigQAbgAJoAXgA6IAE58+YUsoB8YgPSSp27iFLwEPNhAHkmABiRYsIAL54a9RswBW5XgKERJmUAVzMZUjYVCEtlAG5FakSENhkAJXUwAFk+KHMZeRlgRJlSiNopeAB9YnMoJBlCEOpLa2oACgBKIpKysr09GQBlYSgZWhkVeABHEPhImTY+RZZ4GQAjWh4Aa1HF5ZCAByhaIRW1gHNpYUnMjHvevpl+alI+BAxYPgv25VIK+DKToJah9NyJR4yC7wNhVNQaUgNJotKwCLo9UFPUoDGQAQVB8AAHvRDghJvNDjY1oQ1GANltdtQoPcMJC+hkNDk8rAMPDNAUZFRlNBlEhlOg0ABWACcyjwyjoDFFCs8cuUeVIPGih1RSWQ6vmWogOrayhcAF0QWD5dQXCDEsjWgJ0plSOjipjSlM2CEVKCPVjSgIINQIGwkc0nR1ugHA+zMlzzBhobC+W7gWyyuDPU8pBB4AB3CMotruzNY72+0FgdoAckMtbwgvLcZkNdrLCwjZktY5mlrnRtrcD7bYtHWCG7FBbw9KfcTPLTGDAtEO7UduvaUlosDmMZns76lb9zZzh8Po5UU4P59bo6g3drADlPAOh7eP6V742b5-W8Bsz-IDT2A0C2zrENDhCNgfzPMCgNjeCkMWABPQ54AaZQhEJNg1Tg5CgIECdfQadp4E6eRtEQgj4O3Xd4AwRU1kKBixxUFMMDouYrRopD51yJN-kqGp81gKAyIzfDeNvQDpOAriMJkBTGM8d85PPFxOl-ZDzW04DBz029zQMqTQMva9TN478m1rAARQ1tV1N9DLA6yQPUu862wtj4FoWCPPPaiAsPIjdxUUjyMooLgsPZSNSNE1nRYjA2I4hSeJi29+O5DAhOqWoxIkjLMuHWSSuHBSGjihzjV1FzpLK8qtMsmjjPqj9dJav9mp04rP00ly2q64y+qzSEXESCaklDQgZHaKA+B4EIGEEZMYQAUQQFa2AAIRQgBJcTazTAcZAAQkKagQlgWB9xzMBlz4Zo2HmxbluENg1rYTb4G2vbDrrE7BxdBFJKmkwzAsXVbBASVHBQVx3BAJjRAwHhSD8EAXkCNhRFcc0CFgENtlsKhkc8URIDYFhoi4AhfS4Jh2DYQ5EQGZpDm2C40Y0PQqZpkgAAEsAwOwMAAFj5sMBZ5SBqAwXwTDYNCvE1Rz8ZcIA)

**Comment by isiahmeadows** [comment] 2020-11-08 23:04
@shekharsom The contents of `<textarea>` elements are used as the initial value, not the current value. In the spec, [it's reflected in the `defaultValue` attribute](https://html.spec.whatwg.org/multipage/form-elements.html#dom-textarea-defaultvalue).

It's indirect, but long story short, we're not aligned with the spec. (The fix might be as simple as removing that extra logic, but I'll have to modify the mocks to verify it's the right fix.)

**Comment by pereriksson** [comment] 2020-11-09 00:47
I'd just like to extend my appreciation for all your hard work on this issue.

**Comment by dead-claudia** [comment] 2022-02-21 19:19
Fix is simple (it's just within `setAttr` in `render/render.js`), but you might be able to beat me to fixing it. But yes, it's okay to block release on it.

**Comment by StephanHoyer** [comment] 2022-02-25 12:19
Already fixed in [@next](https://flems.io/#0=N4IgtglgJlA2CmIBcB2AjAOgEwGYA0IAzvAgMYAu8UyIGAFuWLCAQGYQKHIDaoAdgEMwiJLQZMWIUgHs+lOTQA8UCADcABNAC8AHRAAnadLCE9APkUB6FarOTiZchFldRABiRYsIAL55+QiK0AFZcBDJy8AqiegCuxOqE5PoQFHoA3Dp8WQjk6gBKRmAAstJQJOpa6sBZ6nWJAqrwAPrsJFBI6qyxfBTOfAAUAJTVtfX1lpbqAMpRUOoC6vrwAI6x8Enq5NJbdPDqAEYCpADWc1s7sQAOUAKUu-sA5mpRS0UYH2N1fllf6o-wcjNQzGQidbq9JyyYajPjjcaTdQAQTh8AAHkIrgglhsri59qxDGBDscznwoB8MH9xoVjKVyrAMCCTJV1Lw9NA9Eg9Og0ABWACcejwekEwi5osCwr05UIpBSVyh2WQMo28ogiv6eh8AF1MnD6j8+D59VkIX1ZAUioQYTUDXVluRYvo4Xb4fVZBA+BByOCehbBiM3e74bSSmUSBgAUDmTahvqQ+ojYnVBB4AB3P2Q-q26khx3OuFgAYAchsJbwbLzibqxZLdCwFfUJbDhBLQxF9pr4zr5AEBwQTe41e79TD9MjsYwYAEVwG5qVA1UAlg6yDI9H8ILLqrXc3m97+iHG-33d7UCbJYAcoF253Tw-6ueKyfH93gMm31-h3uv2+616VyxOQL6-n+f7BuBUHwuQACeVzwJ0eiUGi5DSmB0F-rIA7Op044RoyhCNC0bSwFA96YZRy6roh6jUesGBivAFGUV+PhDK+rE6px4EdjxD46nxGHgYex7CaxtaluQF6ViWAAiaoKkqd78dBz6Vj+Emnr26J9ssAigVpb6QUZb7Yau+h4UUE6EcRrRpmRLGmZun7OZu9HwBgsrqpqsiqaxHHiRJgn+Y+3FBW+gWUXqoWGlFAnxd2gkJiGPh-Glxq-N6rDqAMUDSKQsTCHIUaAgAoggxXkAAQrBACSUClrG7bqAAhFUfCxLAsDrl2YDTtIPTkHlBVFVE5CleQFXwFVtUNU11p3laoLxlkGX2CQ8ABq4IB8lgSBoAAHL4-ggExNAYKQhBhFIsjyOQNC+DqBCwF6JyuLwZ2BDQkDkHQKSMqEkjOswogMOQVxgpM+gCOmUY+nQsQHPE8D6BE92XcYljFAjAMAFLTJYv3-RwGChJYfC6UTuOk0DBBwQhNBykpT0+EAA)

**Closed** 2022-02-25 12:19 UTC
Labels: Type: Bug, Type: Release Blocker

**Comment by kevinfiol** [comment] 2022-02-25 12:28
> Already fixed in [@next](https://flems.io/#0=N4IgtglgJlA2CmIBcB2AjAOgEwGYA0IAzvAgMYAu8UyIGAFuWLCAQGYQKHIDaoAdgEMwiJLQZMWIUgHs+lOTQA8UCADcABNAC8AHRAAnadLCE9APkUB6FarOTiZchFldRABiRYsIAL55+QiK0AFZcBDJy8AqiegCuxOqE5PoQFHoA3Dp8WQjk6gBKRmAAstJQJOpa6sBZ6nWJAqrwAPrsJFBI6qyxfBTOfAAUAJTVtfX1lpbqAMpRUOoC6vrwAI6x8Enq5NJbdPDqAEYCpADWc1s7sQAOUAKUu-sA5mpRS0UYH2N1fllf6o-wcjNQzGQidbq9JyyYajPjjcaTdQAQTh8AAHkIrgglhsri59qxDGBDscznwoB8MH9xoVjKVyrAMCCTJV1Lw9NA9Eg9Og0ABWACcejwekEwi5osCwr05UIpBSVyh2WQMo28ogiv6eh8AF1MnD6j8+D59VkIX1ZAUioQYTUDXVluRYvo4Xb4fVZBA+BByOCehbBiM3e74bSSmUSBgAUDmTahvqQ+ojYnVBB4AB3P2Q-q26khx3OuFgAYAchsJbwbLzibqxZLdCwFfUJbDhBLQxF9pr4zr5AEBwQTe41e79TD9MjsYwYAEVwG5qVA1UAlg6yDI9H8ILLqrXc3m97+iHG-33d7UCbJYAcoF253Tw-6ueKyfH93gMm31-h3uv2+616VyxOQL6-n+f7BuBUHwuQACeVzwJ0eiUGi5DSmB0F-rIA7Op044RoyhCNC0bSwFA96YZRy6roh6jUesGBivAFGUV+PhDK+rE6px4EdjxD46nxGHgYex7CaxtaluQF6ViWAAiaoKkqd78dBz6Vj+Emnr26J9ssAigVpb6QUZb7Yau+h4UUE6EcRrRpmRLGmZun7OZu9HwBgsrqpqsiqaxHHiRJgn+Y+3FBW+gWUXqoWGlFAnxd2gkJiGPh-Glxq-N6rDqAMUDSKQsTCHIUaAgAoggxXkAAQrBACSUClrG7bqAAhFUfCxLAsDrl2YDTtIPTkHlBVFVE5CleQFXwFVtUNU11p3laoLxlkGX2CQ8ABq4IB8lgSBoAAHL4-ggExNAYKQhBhFIsjyOQNC+DqBCwF6JyuLwZ2BDQkDkHQKSMqEkjOswogMOQVxgpM+gCOmUY+nQsQHPE8D6BE92XcYljFAjAMAFLTJYv3-RwGChJYfC6UTuOk0DBBwQhNBykpT0+EAA)

just curious because i was looking at this ticket, but where specifically in `setAttr` was this fixed?
