### ISSUE TITLE
Further minimalization and greater performance

### ISSUE THREAD

**Issue by mikesmullin** [MithrilJS/mithril.js#2187] opened 2018-06-30 05:03 UTC
Being a DIY and minimalist no-dependencies kind of guy 🤓 ,
and after using and enjoying Mithril for a while,
I recently realized there are only a few things unique to Mithril that I commonly use:
- `m()`
- `m.render()`
- Components
- Lifecycle methods
- Keys

...and some things I want to use but are initially tricky to have without fully understanding and possibly modifying Mithril internals:
- integrating `m.route()` with CSS3 `transitions`/`animation` made to look like page transitions
- ECMAScript Modules (`import`/`export`)
- Redux-like state and history features
- ES6 syntax for further minimalism
- Javascript performance optimizations; care taken to:
  - reduce time to apply DOM changes
  - avoid memory leaks and unnecessarily long garbage collection
  - render at a high frame rate compatible with `requestAnimationFrame()`
- Potential for management of WebGL + CSS3 objects using Virtual DOM approach

Additionally, while thinking about it, I thought to include a few extra features:
- JXML serialization format:
  - like JXON but with a few improvements by me
  - still JSON though--not like JSX which needs babel
  - used internally because its compact in memory
- also the option to stop using `m()` and instead just return the JSON directly from a `Component:view()`
  - because its easy--possibly easier--for humans to read and write
  - but more importantly it eliminates the time that `m()` would normally take for string parsing and serialization, improving performance, and reducing memory consumption to the furthest extent possible

Therefore, I thought about it for a while, and wrote a little prototype in a few days, which I'm now sharing here to gauge feedback from the community as to whether I'm onto something here or not, which might be merge-able into some future upstream major release...

Please see the following demonstrations:

- [Mini-Mithril.JS w/ JXML performance option](https://codepen.io/mikesmullin/pen/BVvEzL)
  **note:** critical code ~228 lines or 7,874 bytes, but remove `m()` and properly `min.js.gz` its 1.3kb
- [Mithril + Mini Redux](https://codepen.io/mikesmullin/pen/mKzyzx?editors=0010)
  **note:** critical code ~30 lines or 1,961 bytes

One idea for how this may be compatible with a community release would be to split Mithril lib into separate modules and provide common bundle configurations like `mithril-jxml.min.js` or `mithril-m-jxml.min.js` or `mithril-all.min.js` which would be the kitchen sink (incl. Streams and Redux), etc. Its funny that a library which is already under 8kb would consider modularizing, but I think its practical here, since we are minimalists, after all...

Feel free to borrow any ideas.
I'm interested in any feedback.
If no interest I may publish and maintain on my own repo someday.
Thanks!

**Comment by isiahmeadows** [comment] 2018-07-04 20:11
Although most of the discussion has been on Gitter (with a few bits here on GH), there's been consideration of splitting Mithril's `m.route`, `m.request`, and friends from core, which amounts to 90% of the bloat (exposing the internal `requestService` will make this easier). If you remove those, `m.mount`/`m.redraw` combined amount to only about 15% of the size at most.

But just FYI: stripping it to the core (rendering + `m.mount` + `m.redraw`) only shaved it down from 8.9K to about 5.5K, 5K if you strip it down to `m` + `m.render` + `m.vnode`. And by that point, the only thing you can really remove is `m` (replace it with an object) to drop it down to about 4.3K. `m.render` relies on `m.vnode` internally, so you can't really split them apart.

So if you're somehow reducing it to 1.5K, you're removing a *lot* of core functionality in the renderer itself. And for performance reasons, we can't really do that without completely redoing our bundling pipeline. We also wouldn't like the code duplication this would bring.

**Comment by mikesmullin** [comment] 2018-07-16 07:35
So my core consists of basically just `m.root`, the `VNode` class, and `m.redraw()`, and its 6.3K minified or 2.7K gzipped. This supports components, lifecycle, etc. 

I started a repo and some docs to explain exactly what is included. 

https://mikesmullin.github.io/m-js/

The entire kitchen sink is 30.5K unminified and that includes a minimal Redux clone, a Hot Module Reload (HMR) feature like Webpack has, and a bonus 70-line Markdown-to-JXML parser.

I am still refining the size after completing the featureset I wanted. There is some fat I can still cut without sacrificing functionality.

I am now curious to try the benchmark tests used to compare Mithril vs. React and others. I would like to see if this performs any faster using JXML.

**Comment by isiahmeadows** [comment] 2018-07-16 18:04
@mikesmullin Welcome to the world of front-end framework design, BTW! 😄 But in all seriousness, Mithril is pretty hard to beat in order to get a similar feature set at a similar speed. And I'm curious what it'll turn out like.

And this wouldn't be the first front-end framework inspired by Mithril:

- [Bobril](http://bobril.com/)
- [Kivi](https://localvoid.github.io/kivi/) (indirectly)
- [DOM ViewModel](https://github.com/domvm/domvm)
- There's probably others I haven't listed here and/or aren't aware of.

And Mithril itself drew some inspiration from a few places:

- React was an inspiration for the v1 lifecycle methods, but we decided to simplify them by taking only the minimum necessary.
- [Hyperscript](https://github.com/hyperhype/hyperscript) syntax was used for the DSL.
- Before 1.0, there were a few things that dated back to @lhorie's issues with Angular v1, what led him to write this:
    - Components used to have a separate view + controller, and you'll see remnants of that laying around any time you see a `controller` component method that isn't used directly.
    - There used to be an `const prop = m.prop(initial)` that returned a getter/setter, where `prop()` gets the value and `prop(value)` sets it. `m.withAttr` was designed initially with that in mind, so you could do `value: ctrl.value, onchange: m.withAttr("value", ctrl.value)` to get bidirectional attribute binding easily on form attributes, etc. without having to keep explicit support for that baked into core. This was replaced in v1 with streams, which also carry a similar API for getting/setting.

**Comment by isiahmeadows** [comment] 2019-01-17 17:18
Closing this as there's nothing actionable here.

**Closed by isiahmeadows** 2019-01-17 17:18 UTC
Labels: enhancement

**Comment by ancmikesmullin** [comment] 2019-04-10 04:45
Thanks for the attention and feedback. I just wanted to add one more note FWIW.

I noticed while using Mithril that it can be difficult in a few situations to serialize the markup you generate with it.

It might be nice to have for example a `m.toHtml(vnode)` which can take a mithril vnode and output pretty html text.

Similar to that, it may be nice to input a serialized JSON (JXML) document (as defined in m.js docs above, for the example below) and have it inflated into a full blown hierarchy of instantiated mithril vnodes. ie. `m.parseJXML({...})`.

Below is one such implementation of that:

```js
const jxmlToM = (o, _tag) => {
	if (Array.isArray(o)) {
		return _.flatten(_.map(o, jxmlToM));
	}
	else if (Utils.isObject(o) &&
	    // must not already be a mithril vnode instance
	    // (caused by depth-to-root/bottom-up hierarchy traversal)
	    !(_.has(o, '_state') && _.has(o, 'attrs'))
    ) {
        const children = [];
	    _.keys(o)
	        .filter(k=>'$'!==k[0] && '_'!==k[0])
	        .forEach(k=>
                children.push(...jxmlToM(o[k], k)));
        children.push(...jxmlToM(_.get(o, '_')));
	    if (null != _tag) {
	        const attrs = Utils.reduceObject(o, (acc,k,v) => { if ('$'===k[0] && '$'!==k) acc[k.substr(1)] = v });
	        return [m(_tag, attrs, children)];
        }
        else return children;
    }
	else return [o];
};
```

This works for me presently.

I use it with another bit of code I have, for example, a custom Markdown-to-JXML parser:

```js
const stylizeMarkdown = input => {
    const vnodes = Array.isArray(input) ? input : [input];
    return _.map(vnodes, vnode => {
        // multi-line code block; apply coloring
        if (_.has(vnode, ['pre', 'code'])) {
            return m('code.boring-grey', jxmlToM(_.get(vnode, ['pre', 'code'])));
        }
        // inline code block; apply coloring
        else if (_.has(vnode, 'code')) {
            return m('code.inline.boring-grey', jxmlToM(_.get(vnode, ['code'])));
        }
        // external link; add icon
        else if (_.has(vnode, 'a') && /\/\//.test(_.get(vnode, 'a.$href'))) {
            _.set(vnode, 'a.$target', '_blank');
            _.set(vnode, 'a._', [
                _.get(vnode, 'a._', ''),
                m('i.fas.fa-external-link-alt.ml-1'),
            ]);
            // fall-through
        }
        return jxmlToM(vnode);
    });
};
```

`stylizeMarkdown()` is a callback function I can pass to the `markdown(mdText, ...)` parser function, which will invoke it on every visit to every html element as its translating, to provide an opportunity to modify it (e.g., turn a boring code block into a styled one with perhaps certain colors or a full blown syntax highlighting js component). Whether I provide the `stylizeMarkdown` or not, the `markdown` function will output JXML, compatible with my `m.js`. But I found a case where I wanted to use it with Mithril, so the first function let's me take it the last mile `JXML` -> `m()` vnodes.

In general, there are probably more good reasons for Mithril vnode data structures to be marshalled in/out (serializing across the wire, or for storage). Nobody likes parsing HTML, so a JSON-based data structure is ideal IMO.

Sharing upstream case this helps.

**Comment by isiahmeadows** [comment] 2019-04-11 03:35
@ancmikesmullin To answer each suggestion:

1. We've had an HTML renderer for a while: https://github.com/MithrilJS/mithril-node-render. Just the hydration side of things [doesn't quite exist yet](https://github.com/MithrilJS/mithril.js/issues/1838).
1. Mithril's vnodes *are* JSON-compatible. It will screw with the object shape (so you lose a few perf benefits of our internal model), but it otherwise *will* work. The only catch is that you can't provide event handlers or component references, but that's easy enough to address.
