### ISSUE TITLE
Access vnode.dom in event handler

### ISSUE THREAD

**Issue by andraaspar** [MithrilJS/mithril.js#1762] opened 2017-03-31 13:03 UTC
It seems to work. In TypeScript we discourage it (have to cast `Vnode` to `VnodeDOM`). The docs say [vnodes should not be memoized](https://mithril.js.org/vnodes.html#avoid-memoizing-mutable-vnodes). Is this valid, or does it count as memoizing?

```JS
var data = {
  text: 'Click me'
}

var App = {
  view: function(v) {
    return (
      m('button', {
        'onclick': () => {
          data.text = v.dom + '' // Can I do this?
        }
      },
        data.text
      )
    )
  }
}

m.mount(document.body, App)
```

[Fiddle here.](https://jsfiddle.net/andraaspar/9zfwmhjc/)

**Comment by pygy** [comment] 2017-03-31 13:13
You can totally. By the time the event handler fires, the `vnode` will have its `.dom` property (but typeScript has no way of knowing that AFAIK).

If we change the signature of event handlers to get the `vnode` as second argument, we could define it as `VnodeDOM`...

It doesn't count as memoizing, no. The real problem with cached vnodes is if you try to display a vnode more than once at a time on the page.

**Comment by andraaspar** [comment] 2017-03-31 13:34
I see. So the docs warn about something like this:

```JS
var data = {
  text: 'Click me'
}

var button = (
  m('button',
    data.text
  )
)

var App = {
  view: function(v) {
    return (
      m('div', {
        'onclick': () => {
          data.text = v.dom + ''
        }
      },
        button,
        button
      )
    )
  }
}

m.mount(document.body, App)
```

Which obviously does not work. Maybe a wrong vs. right example would clarify.

**Comment by pygy** [comment] 2017-03-31 13:51
That's another problem with memoized nodes they are not updated, by design... The only go through the init/create and (before)remove phases.

**Comment by isiahmeadows** [comment] 2018-08-28 12:03
Closing this, since you can always use `event.currentTarget` (from the event handler's argument) to access the raw DOM node in event handlers. The main exceptions here are lifecycle methods, which provide vnodes for you to use anyways, so there's no issue there.

**Closed** 2018-10-28 23:50 UTC
