### ISSUE TITLE
Unnecessary DOM node remove/append

### ISSUE THREAD

**Issue by hankeypancake** [MithrilJS/mithril.js#1999] opened 2017-10-23 12:46 UTC
When rendering a list of items from any kind of fixed length array where you append new values and remove the overflowing values, mithril will behave correctly up until the array reaches maxlength, then start removing all DOM nodes and appending them again if they should still be rendered. This will kill all css transitions for styles that changes from state a to state b.

The nodes onremove-hooks will not be triggered

## Expected Behavior
Only the removed nodes should be removed from the DOM

## Current Behavior
All nodes are removed, and the ones that shouldn't have been removed gets appended again

## Possible Solution
I have no idea

## Steps to Reproduce (for bugs)
This jsfiddle demonstrates the behaviour: https://jsfiddle.net/hankeypancake/aa4c9gnr/
It has contains two implementations: one with react which handles this correctly, and one with mithril. Clicking one box will restart that particular app.

The issue appears when the boxes are 'full'

If you, before the issue appears, set a DOM node removal breakpoint on one of the later nodes in chrome devtools, you can see that it get's removed

## Context
I was just throwing a simple moving time series visualisation together when I encountered it.

## Your Environment
* Version used: 1.1.5
* Browser Name and version: Any
* Operating System and version (desktop or mobile): Any
* Link to your project: Private, jsfiddle is provided

**Comment by isiahmeadows** [comment] 2017-10-23 18:10
It's actually a `key` bug - Mithril should know better than to replace keyed subtrees that just happen to be moving backwards (i.e. earlier in the DOM).

**Comment by isiahmeadows** [comment] 2017-10-23 18:42
After toying around a little, [it works with fragments](https://jsfiddle.net/y33be9ak/) as well as [elements](https://jsfiddle.net/npzu0h9e/).

**Comment by isiahmeadows** [comment] 2017-10-23 18:46
It appears to fail on everything, so I suspect it's an issue with the diffing heuristics.

**Comment by hankeypancake** [comment] 2017-10-23 19:00
as per the gitter discussion: it works if we reverse the array generation to add from the end instead of add from the start

**Comment by pygy** [comment] 2017-10-23 19:48
As I thought the problem lies with the way DOM nodes are handled (that's what I mean when I asked about elements vs component on gitter). The hooks fire normally.

The culprit is the [unconditional `insertNode`](https://github.com/MithrilJS/mithril.js/blob/bd83b32709453ea78b01585078f04e886100d8e4/render/render.js#L239) line in the mapped diff loop. [If you comment it out](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgBMIA3AAmqgzhwAvAB0QGAA4SxAPhFpu3LBGKEATtETzF7LtwhtRIZao1QAtJOkgZLAPQdOctPccyQAXwrpsuRAQArBCo6BiZiPFC4Yn0wtU4MKAAVCBxuIW4AVgAGbPlYGIUMvLQomIBzGGIAYVoodO4ACgBKdJluYHkRYjUqgFc1BU6FRX02RG40AGopim1RhKg+mAmAWQxVfDVaPrQ2RvXNtQw92iwW7gAqbgBGXOb5j3kntHky3jq4BuQAXTf6aLcDBsNi1eoZC5CdrDRR0KBwfC7OCECBgYiNSo1OotB4jVGNOEI2BocqqbjtADMrUJ+GJpMIDQpz3+aEB6wgaFqWAk9HCDRh3Ho1F6GxWTWA3Giou4HlaUI681hALqMFptHKjQA5MKYNKsBgOZrcYovPNOBAYAB3CaNCVSxgyuXQ+bdXrEAYKc6axz4ULEA1oGBqTUUBUjRTdIVQCDUADWE3tqqlamIiploZp+okjQJdVDECdYdGo3e0QAnrB+WnixpyiQbRArtwAEzZVpTbiaiQADxD1dGhBgEDrxAmcPwi2W3A7moApJr+y9i4o3R6lFqfXCQ0Xl4py7AE8QKzBuHNw8vYzAy2O6vgDGfd4ohSLGBcBY+PqyVWqNZrqp3pw+KA7zYY1H1Nc9i3oPoJDYUU337Ysom-KB1S1ABVACO3HAwwN3CCP3oXosFoTgYAQyDl2Q2Afy1AAlLCgJAvDlyXViWNlMCXheeQsC2Jg2CDRo2Foag+hwBh8ExABRWAJOIAAhMsAEl9k1Ex1GgSwpCNUNznZTkzh5QMGGaXE4CqFIcB2dEWihAVgVBbEwL43o9iEkSxPkqSqlkmB5KU1StQ0sxtIkXT1wMrljPCMyIzQLwsnueQLOIKyYBsnNmns+ZHLBFp5lcgSPNE8Twh84g-IClS1JCrSrAi-SA2i3lTNabhnlDO5ktZSzUgyvpbOymQHJBfKXP49y1GE0rvJkuTwkC2qVE0iwGuaPSDmaozWuIOKOoSrqcjbFK+uswaspykY8ucwrJsE6bPLKyT5v8xaauClbQvWzaop2ky9vazqW1yE7erS-rMrskbcrG26RiKqaZq88rXuqoL1K++qdI2yLtu5Xb9uB5tjtxTxvBATAcDwX1BEoGh6EYZh-BIMhQwAI1oNgyx3Qdh3rW5clnABueZLQMVQJm6kX5gkRyOXKCZslFkZObUB6lZVl5Oe5ncODgCR+GvbgwFgbsVcURJhzQcwVH8uAx3CIMLZNs3zA4XpqGICB6BvJYsDQF2Aj6aJUTLcw-XCR24i1+R8CsHdGG7YhLGjco0Gjxg1BdsBGfMMBsGgY24BOOBzAsjQwBzvO4AgAAvMU7h7WO0F9RmAyDHd9TUcoOQmTIe24bJBebsWJcICYADZslHkY+ZHCYAHYZ-N2XaFr73fe4Xp+G9siXbVjXbkHuA6gMbfynZjBGmyChb-v-AABZcReNv6gFHpS5UH2M6BKB6myPgZsXxoyBgwNnNeG8f4TAwOzU+SxGAHwwHGco2xdjjAvlfG+d8cGAMyM0A+tBiDEDOJreY88BYrxduLNgksQazxeJ4H4VBQGxgQCgHw1N-B1XIFQAY5AWbEIkA7OwdhdgSFjOUNuWA7A8IAAI3HwIozIsisbASCPTI8Eg-AgA0VQOWxBqCDnYcgUxt8QBdFTFY7oNirEgGYcgG4VBRH2IoMgcxHIK7EAAHK0FcTcSeFAbgAA4KDNhCdkUJ4TgmRJ+D8Dw8SgA), the sample works properly (but doing that causes regressions in the test suite IIRC).

I suppose that adding from the end uses another branch...

I think I've already pinged @lhorie about that line in another issue, it weirded me out...

**Comment by thysultan** [comment] 2017-10-24 20:41
Her is a small unit spec that exercises this case.

```
7, 6, 5, 4, 3, 2 [next]
6, 5, 4, 3, 2, 1 [prev]
```

The least no. of DOM ops would be to create and insert 7 before 6, then remove 1, though based on the fiddles behavior it currently might create(append) 7, move(append) 6, 5, 4, 3, 2 then remove 1. to get to `7, 6, 5, 4, 3, 2`.

**Comment by hankeypancake** [comment] 2017-11-15 14:23
Could this be added to the 1.2.0 milestone?

**Comment by pygy** [comment] 2017-11-16 23:12
@hankeypancake there are other updateNodes bugs that I must fix before tackling this one... Hopefully we'll have i in the next release too.

**Comment by pygy** [comment] 2017-11-23 14:34
This is actually a dupe of #1791 

Closing this one (it is still on my radar, @hankeypancake feel free to subscribe to the other bug for updates).

**Closed by pygy** 2017-11-23 14:34 UTC
Labels: bug

**Comment by pygy** [comment] 2018-05-29 21:55
So the fix has been merged into `next`.
