### ISSUE TITLE
CSS Variables not passed through when using style object

### ISSUE THREAD

**Issue by soulofmischief** [MithrilJS/mithril.js#2324] opened 2018-12-02 22:31 UTC
### Mithril Version: x.x.x

2.0.0-rc-1

At least in JSX, when using a style object vs string, CSS variables are not passed through to the style attribute.

## Expected Behavior

```
style={{
  '--color': 'red',
  background: green,
}}
```

should be functionally identical to

```style={ '--color: red; background: green;' }```

## Current Behavior

The former example results in ```<div style="background: green;">```

The latter example results in ```<div style="--color: red; background: green;">```

## Possible Solution
Probably just incorrect handling of symbols / string identifiers, I'm guessing that property accesses relevant to the style code need to be changed to all use bracket notation. Point me to the right module and I'll look into it.

<details>
## Your Environment

* Browser Name and version: Chrome 70.0.3538.110
* Operating System and version (desktop or mobile): Fedora 29 (Desktop)
</details>

**Comment by isiahmeadows** [comment] 2018-12-02 22:33
Duplicate of #2192

**Closed by isiahmeadows** 2018-12-02 22:33 UTC

**Comment by soulofmischief** [comment] 2018-12-02 22:35
@isiahmeadows Are you sure? Because passing through variables does work, I'm using it in production, just with a style string vs an object. CSS variables _can_ be specified in the style attribute so I didn't think it was a duplicate.

**Comment by isiahmeadows** [comment] 2018-12-02 22:37
@soulofmischief It's about the magic `style: {...}` attribute, not the string version. A fix has already landed in #2308, and will make it to the next v2 release candidate.

**Comment by soulofmischief** [comment] 2018-12-02 22:37
Awesome. Thanks!
