### ISSUE TITLE
pass attributes to all children automatically

### ISSUE THREAD

**Issue by Mwni** [MithrilJS/mithril.js#2607] opened 2020-06-29 23:37 UTC
Is there a way to propagate data to all children without having to pass it on via `attrs` manually?
I'm thinking of something like a shared (downstream) state, that is available to all children automatically, regardless of how many levels deep.

For example
```
const RootComponent = {
	oninit: vnode => vnode.broadcast.foo = 'bar',
	view: vnode => m(ChildComponent)
}
```
and then on any child component several levels down have access to `vnode.broadcast.foo`

How could this be implemented?

**Comment by osban** [comment] 2020-06-30 15:26
@Mwni wouldn't it be easier to just use global state?
```js
const broadcast = {}

const RootComponent = {
  oninit: () => broadcast.foo = 'bar',
  view: () => m(ChildComponent)
}
```

**Comment by isiahmeadows** [comment] 2020-06-30 19:33
Closing as a duplicate of #2148.

**Closed by isiahmeadows** 2020-06-30 19:33 UTC
Labels: Type: Question
