### ISSUE TITLE
Mithril throws an error when two or more sibling components render content via m.trust

### ISSUE THREAD

**Issue by spacejack** [MithrilJS/mithril.js#2498] opened 2019-07-31 20:25 UTC
When 2 or more instances of a component that renders `m.trust()` content are rendered, changing the html string passed to `m.trust` between redraws will cause Mithril to throw an error.

**Mithril version:** 2.0.3

**Browser and OS:** All

## Code

[flems example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgAcA+AHTQAJeAKrQDmw2L3oxeAIwCuxYvV5haUKLQDuMACYyAnrwxpaxQjABOvRb3MYIcKTAAe1GG2IR6PFgHpO37QgAN14IbQBeLhAMNjYo7j5ebx9AoI5KEAdYag96BEQQAFZEADYQAF8KdGxcAvwAKwQqOgYmYjwgjEsAQVpzACEAYVosNkkGXnDeAAoASkmOXmAeflhiQ2lJ3gByDG2VmxhiWXM+YF4giBgNRBmg420YefDF5cT+cyOTvixp7dTthReMgDvx+L9tnIFPRAUtQWD+PRqFAINQANa3OYLJYbLYYTbhQk7Pa8AD8O2k214t12VPK8P4lR2QlEsG2swoDN4EIBnPeCI2fIFYKw+GI5lkcGI03xkyJtLJOxYcDYRg43V8KrVVJpytVaA4-U1+o47K5s3hAF0LYlyvS0PaeJ0erEtm9+Jdrpj7rRHs9XvDPsdTty-ryub9egNhqNxsQORHplGhiMxmg2gn+TbGTxHWhRVhaLIGNNtLRqLIcAx8MIjgBRWBV4j9PQASW0fxibHZQO6sVmGToo2gFjw0nxMHIVCyMBynjQ+RAAEYAAyIADsFSqIEwODw+GocCaNHojGYBQqlqoKLQaPyqB3NTwWAgpnM0Aax5O5AKJGIbDgRAfB8Ys2DRYQDxGHwXzfaAAAEACZ8BXfAAGZoNfQh3ygT8MmIPQ2FqTJqHfdxL3KIA)

## Steps to Reproduce

1. In the flems example above, click one 'Toggle' button
2. Then click the other toggle button.

## Expected Behavior
Mithril should render the content.

## Current Behavior
Throws the error: `Cannot read property 'length' of undefined`

**Comment by isiahmeadows** [comment] 2019-08-01 03:19
That's *weird*. Thanks for the report!

`vnode.instance` should now always be an array for vnodes Mithril created. I wonder if mistakenly a new vnode got passed for an old one somewhere down the line when I updated that code...

**Comment by JandosKh** [comment] 2019-08-03 08:51
I can confirm that there is an issue with vnode.instance. Few days ago I wrote about it in gitter chat. In my code I am using m.trust(outputHtml) where outputHtml comes from server. The error was something like "vnode.instance is undefined".

**Comment by erikvullings** [comment] 2019-08-09 18:26
I also experience the same bug (but not always reproducible!) whereas my tree just contains a single DOM element that uses `m.trust`. The error occurs in `render.js`: 

```javascript
	function removeHTML(parent, vnode) {
		for (var i = 0; i < vnode.instance.length; i++) {
			parent.removeChild(vnode.instance[i])
		}
	}
```
Is there anything we can do to help fix these bugs faster in the release version?

**Comment by cruzmiraback** [comment] 2019-08-09 21:57
I'm also receiving this error in my app on a view that uses m.trust. In my case, it can be easily reproduced by simply calling m.redraw().

**Comment by pdehne** [comment] 2019-08-14 15:10
Same issue here.

I render an svg icon using m.trust, the error occurs when I replace the svg icon with a different in subsequent renders of the component. It throws at the same place as for erikvullings, in the for loop, because vnode.instance is undefined.

I can also confirm v2.0.1 did not have the issue.

**Comment by charlag** [comment] 2019-08-16 12:45
Same error in Tutanota currently.
Is there a patch/fix which one can try to apply?

**Comment by MKRhere** [comment] 2019-08-17 16:39
I have the same issue with `m.trust` and thought I was going crazy until I found [this official example](https://github.com/MithrilJS/mithril.js/blob/next/examples/editor/index.html) suffers the same fate.

Thanks @cruzmiraback @pdehne I'm going to try and rollback to `2.0.1` for now until a fix is in place.

**Closed** 2019-08-17 18:38 UTC
Labels: Area: Core, Type: Bug
