### ISSUE TITLE
Value "leaking" to other fields

### ISSUE THREAD

**Issue by rbt** [MithrilJS/mithril.js#1869] opened 2017-06-12 00:54 UTC
https://codepen.io/rbt123/pen/vZGRBw?editors=0010

Click any delete button and suddenly the Block 3 input contains the "field2" value from Block 2.

Logging inputFields to the console shows Block 3 correctly (no value). I don't think Mithril is updating the DOM to clear the value if during the redraw.

Occurs in Mithril v1.1.1 in FireFox and Chromium.

**Comment by isiahmeadows** [comment] 2017-06-12 08:05
This is because Mithril has no way of knowing the identity of each input when it patches the nodes. In this case, you'd need keyed fragments (`m.fragment({key: "foo"}, [...])`) or components (`m(MyInput, {key: "foo"}, [...])`) to ensure identity is correctly tracked during patching.

Closing this since it's working as intended.

**Closed by isiahmeadows** 2017-06-12 08:05 UTC
