### ISSUE TITLE
Model value not applied to <select>

### ISSUE THREAD

**Issue by andraaspar** [MithrilJS/mithril.js#1357] opened 2016-10-18 15:08 UTC
### Description:

**Affects Chrome and Firefox.** Edge seems fine.
Certain changes to the options of a `<select>` can make mithril not apply the expected value to the `<select>`.
### Steps to Reproduce:

Please observe the following fiddle:

https://jsfiddle.net/andraaspar/c8m2bux5/

The code:

``` js
const select = {
  view: function(ctrl, args) {
    return (
      m('select', {
        'onchange': m.withAttr('value', args.prop),
        'value': args.prop(),
        'config': (elem, inited, context, velem) => {
          // elem.value = args.prop() // Workaround: Mithril 0.2.5 does not seem to set the value
          console.log(`Select value: ${elem.value} Prop value: ${args.prop()}`)
        }
        },
        args.options.map(option => m('option', {'key': option.value, 'value': option.value}, option.name))
      )
    )
  }
}

const options = [
  [
    {name: 'Zero', value: '0'},
    {name: 'Two', value: '2'},
    {name: 'One', value: '1'},
  ],
  [
    {name: 'One', value: '1'},
    {name: 'Two', value: '2'},
    {name: 'Three', value: '3'},
  ]
]

let appModel = {
  id: 0,
  values: [
    m.prop('0'),
    m.prop('2')
  ]
}

const app = {
  view() {
    return (
      m('div',
        m('p', 'Please observe the developer console.'),
        m('button', { 'onclick': () => appModel.id = +!appModel.id },
          'Click me at least twice'
        ),
        m('br'),
        m(select, {
          'prop': appModel.values[appModel.id],
          'options': options[appModel.id]
        })
      )
    )
  }
}

m.mount(document.getElementById('app'), m(app))
```
### Expected:

The `<select>` to display the correct value from the model. Output:

```
Select value: 0 Prop value: 0
Select value: 2 Prop value: 2
Select value: 0 Prop value: 0
```
### Actual:

The `<select>` displays a random value. Output:

```
Select value: 0 Prop value: 0
Select value: 2 Prop value: 2
Select value: 1 Prop value: 0
```
### Workaround:

Set the value of the element directly in the `config` callback (line 8).

**Comment by james-m-henderson** [comment] 2016-10-27 12:31
This may be a duplicate of: https://github.com/lhorie/mithril.js/issues/1091, which is fixed in the "next" branch.

I used your workaround and it fixed the issue for me (I'm on v0.2.5), so thanks for posting this.

**Comment by isiahmeadows** [comment] 2016-11-23 09:56
[Not reproducing on `next`.](https://jsfiddle.net/c8m2bux5/5/)

**Comment by isiahmeadows** [comment] 2017-07-13 00:49
Closing - last v0.2 release has been cut.

**Closed by isiahmeadows** 2017-07-13 00:49 UTC
Labels: 0.2.x, bug
