### ISSUE TITLE
vnode.parentVNode

### ISSUE THREAD

**Issue by czb** [MithrilJS/mithril.js#1952] opened 2017-08-30 16:23 UTC
It would be great to have access to vnode.parentVNode in the view function.

Scenario: Input element needs to know where in a form structure composed of groups, arrays of groups etc. it resides. This is useful to automatically serialize / parse data in the vnode form structure.

Without this feature I will probably need to take the whole vnode tree before sending it into the m.render function and preprocess it (inject location info into attributes of certain vnodes).

**Comment by isiahmeadows** [comment] 2017-08-31 04:22
Closing this as a dupe of #1427. Please read the discussion there, and if you feel that doesn't sufficiently address your questions, feel free to comment there (and I'll re-open it).

**Closed by isiahmeadows** 2017-08-31 04:22 UTC

**Comment by isiahmeadows** [comment] 2017-08-31 04:23
Duplicate of #1427
