### ISSUE TITLE
Uncaught TypeError & DOMException when rerendering

### ISSUE THREAD

**Issue by MynockSpit** [MithrilJS/mithril.js#2103] opened 2018-03-10 21:55 UTC
This is a super bizarre error. Seems like it happens semi randomly. I was able to narrow it down to a reproducible example. Hopefully you guys can get more from this than I.

## Expected Behavior
Changes to data and rerendering should not orphan elements and fail to delete them.

## Current Behavior
Changes to data and rerendering sometimes (seemingly randomly) fails to delete elements.
Throws either `TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.` or `TypeError: Cannot read property 'parentNode' of null`

## Steps to Reproduce (for bugs)
https://stackblitz.com/edit/js-mennea

The project has a working example. To see behavior, open the console and click the 'Regenerate x1000' button. Errors will randomly happen.

## Context
As the example alludes to I have a tree of folder-like things that I want to display in a tree structure. Based on navigation, I want to be able to show a parent folder with child subfolders, then open one of the subfolders and view it as root. (Generic file system.)

## Your Environment
* Version used: 1.1.6
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop

**Comment by MynockSpit** [comment] 2018-03-11 20:03
After playing with this more, it seems like these errors go away if you remove the uncertanty.

The first block causing problems is fixed if you always insert a node in it's spot.

This ...

     if (item.children)
       output.push(
         m('.child', item.children ? generateItems(item.children) : ''),
       )

... becomes ...
    
    output.push(
       m('.child', item.children ? generateItems(item.children) : ''),
    )

... or ...

    item.children ? m('.child', generateItems(item.children)) : nulll


The second block is fixed if you insert a mithril element instead of an unknown number of items.

This ...

    output.push(
      someSizedArray.map((item, index) => m('.row', 'some row'))
    )

... becomes ...

    output.push(
      m('', someSizedArray.map((item, index) => m('.row', 'some row')))
    )

Still not sure what causes this in the first place.

**Comment by tokafew420** [comment] 2018-06-08 17:16
I'm facing the same issue (using v1.1.6) and finally was able to track it down. See fiddle: http://jsfiddle.net/tokafew420/e6w8txLd/2/

To reproduce the issue, just step through the example.

The problem arises in a very specific scenario and chain of events. I just started digging through the code so I'm not too familiar with it but I'll try to explain what I think is happening in my example.

Required state: 
- Must use document fragments.
- Must get into a state where a pool is created.
- Must get into a state where recycling is taking place.

Steps in example:
- Step 1 - Just a starting point.
- Step 2 - Render different (2nd) fragment with data.
- Step 3 - Reduce the list (This will create a pool)
- Step 4 - Render first fragment again. This puts us into a state to make the bug happen.
- Step 5 - Render the 2nd fragment again with the same length as Step 2.
At this point, the internal state is corrupted already. You can see that the list is NOT in order.
Line [557](https://github.com/MithrilJS/mithril.js/blob/v1_1_x/mithril.js#L557) of mithril.js will take the `old.dom` (which is now the same reference as `vnode.dom` because of the recycling), and append it to parent. This puts the element at the bottom of the list. 
- Step 6 - Render another state that will cause the nodes to be deleted and this error will happen:
```
mithril.js:816 Uncaught TypeError: Cannot read property 'parentNode' of null
    at removeNodeFromDOM (mithril.js:816)
    at continuation (mithril.js:803)
    at removeNode (mithril.js:794)
    at removeNodes (mithril.js:774)
    at updateNodes (mithril.js:607)
    at updateFragment (mithril.js:653)
    at updateNode (mithril.js:628)
    at updateNodes (mithril.js:537)
    at updateElement (mithril.js:687)
    at updateNode (mithril.js:629)
```
This is because the `vnode.dom` is assumed to be the `first-child` and the removal process uses this assumption and traverses the `nextSibling` property to remove all children of the parent. Unfortunately since the node is moved to the `last-child` position, the `nextSibling` property is null. Hence the error.

Now, the question is...how do I fix this?

**Comment by pygy** [comment] 2018-06-08 19:05
@MynockSpit thanks for the report, somehow I let this one slip, sorry.

@tokafew420 thanks for the repro and analysis.

This was probably fixed in `next` (the pool was heavily reworked) before we decided to shelve the pool altogether for v2.

As a workaround, you can opt out of the pool by setting a hook on the fragment  such as `oncreate` or `onupdate` on the children of the fragment. There's no other way to opt out of it.

**Comment by starsolaris** [comment] 2018-06-08 19:06
This is like #1991 , was fixed in next.

**Comment by tokafew420** [comment] 2018-06-08 20:36
Thanks for the response @pygy 
I was able to work-around the issue by wrapping the children array. This work-around also fixed the issue in @MynockSpit 's example. I simply changed line 53 in his example from
`return output;`
to
`return m('', output);`

I saw that adding a hook will opt out of the pool but when returning arrays it's difficult to add the hook inline.

Looking forward to `next`.

**Comment by pygy** [comment] 2018-06-08 21:15
@tokafew420 For hooks on fragments, you can use `m.fragment({oncreate(){}, [...children]})`. `m('', ...)` adds a wrapping div.

See [here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10REbkYBO+AFYIqdBk2It2nHHgAmGYhhFia9Rsx4B6HQAJC9eMSgBPfQvoByYvoDWaWgHd9EMPuKEYlmDAAO5vpoJjAK+vwCAK7UxFECPt4JbnDBMNTwcBgCZgA6IQAe-rQCdgBu2fpgtFAKMAKpALz6yPn6+sBt7fq5IJg4vYg9IAAqMNi9FF3tvdSE0AoJaIMt092daN1bw-0wK70AQhjU9lC0AOaTa+3s1x13M31c+yAHUef6R3CEV5vbt38thttt1ersXgBVACSvxBjzmCyWK1agLhwLhWzBzyQwwAYuM4glUgBlfwCCAMfQABSgGDQaApl0oD26AIx7XR7J22KGvQAsjAVPooXA4FF4LD2Wz2Zz2ViBjjehC0ESamUwsLReK4JKMawWQBdO7SoEs+V7RUgfFhABGx3sutZU1RHLNTwVvJAAAlsDgBI7MTR5rUkTiUVzZSDzS8xhNmS7trNg4smMiWaaE1H3RbPUcTmcmc6uawjZn9CXjUXtpHQdmXgANAAyn3tBYD5arGYx0ctjZg52OFjzpwu7ZN6zd4MtAHl-PVlBB6BgoPpcTUzs4ov4dfGQePXWWe56ae8KTvO4mg4jU2H0-cy4Gp57p1FTIL21t9WXS3uLwfu3WlpQlgZK0OqOAMOeboIiGN5DOGMp3o8T7DAcgoYB+Tp3jWWYoYcUQLJhNx-tWSHch6wwACIwOqZz+BBxBER22FkUewwAOK+hhu5SiRXZcuRObDMBgQwAxC70Ex+6kQ+tZ4SAVICLQChSYaxprD+5alvkMBFCU5SVMQCQwAA0jAZhNKsfzVLU9RwMgAAMBoUPoej6LGWBdDZdQNI5Br4DBKZoMgABMzleTUPn2U5AXJksyAACzhdZkV2X5sXXsFSUZbBwVOVW3lpTFgXxQAHMl7SFb5xVxUwyAAJylgalAgHAMCwLEi5oAgPClfViAAIxsBw2Z4GoLUSFo0g8BAIH6R0VSpQ0LlGX4ZkWeWVRKVg+jWPgOhKCoajWPkFQCPoACO4rivozTIKWZ2+LSZj1LdwRRFAUDOrkdhPRgFjNAAzA5+T5NU50ABT6I9EBvQNDkIwA3G4AC0KOIwAlPe7Qw+EzR8sohD4GAZwlBDBNePgAh0lYWAQ1jABU+gAGxYz0fxXTA4r4P4UTfBD9O3QAfJYtDUFEDH4JzOTEu16TEGT1g2spZhCzar4K2g1gYwFUAQCc9MY-kX5g1EaCdfQngmPW8MI4LwDs+0dTPa9zRtcQIyzTAtCvhDYBmxbaD26DxCc+Kfn0yHYcwPg3zuMQkfLMQ7j6BD0d+UbCZ8MQNsIw5ifEX9ZiZybaCPQAwrQc0hJSzTomUEAwM4QyC40IuygkhKbAhWxuV4ECpOrxCaxEcuxKkGD6NTaC04ttnnc4EBePoJVMC5NOj3YS-6BgqRtR1jAqQmdNKxrNguTh+j0NQesnEM-vm8nlvB7JsBb3j+gU0TJO0GTX9UzTKugsmaszvPveWYQ1zzzeqtUy5l7IQAUJpPclZdoACV+xMHnIwbW30Ex93mIPM+mwb763sKkLwPhIANDsEPEetsHKeC9qkCGS9rCpEtpPZOOAfbEBcnAWgbg7DOBsHYQgdIPiUP0DaJSzg2oCEziCE+dDz4LWvrfewLcsZtytvwXOdssbsHQZgkI1NGD6AKPoBhuDQb4IMMcOIy4p5MB8oyWxIICEDyviEfQIiBDkLuG5E+1gXLnCwWYmAUJGBYDgBDZA2cAD6YTTHKBgLLA+kCloQwShjA0GNM6BIMP3DhPirDwC1oxY+ENrAhP0Mk7BkTomxPAbETJ88cpBXyRpLoX5S5uX4Kk06lQWmHygT5GBxl1rRW0mgB+gc6nhNSVEsSsSl4rKxuiTu8RNhrJifgLAGB-CsOicLbG3RHq8N5nYO6dxgkuV2fgXYGMLwVW2AInAxIIAAC8wgAEEBDUwBqnEIrh-mAvJoTYmpMBDHLEo8rg+BYBoHOMvAwrN8nE2gFAapkBYC7X0AAaiEXCp5ti1huQhGKZcQRQIKBiPAfQAADEYZg5wAFEAUlCGLiDA0ANQK30LpdIr4fDWEOXOGe5dkzWG8btAAcspGA1ghj+GyFwQQViUjBFoHYWgHhiCstFQquoe1GVrBTrCrAHSliKO2Jc18PM+aEAhiyE+HTakPNXpsAA-AslJjBlkxMtdapgWMhg1OeXcApqIKVUs+hYWl9LUjMsNRypSAghjlzpE4OwCQMDhFAnOUoFhrCqqWMQY1Sqr4eDQB9KAZrUT2uII6-mdx3lpO+X8gF-19mHIFrs+5M9dLaJFm62RtT2FVx8OOrpqJo1bC2QITYVqwDU3OAxCGwBr55sYPTYArAjFNttawEuti+6COzp4QRbUfApykZEGIhIfB6s8N4SwyhJ5eKkaBG0sAsAuShL4pS5jin4GFHYepESJ47LqAwfWTiH3i1WuEWgNphDyzAyMN99AggKHcGAeoTAMgT2SF4ZQQj2F+oaShzYUiSYWBovUCw3CfAbzI1vYglGzZ63sO1Cw4NghcAoYIm0t7YPJ2oMuU2j8uq6OIEkxZjB0kQIUGM+oEM6j+C8Bsroj1dhvQhZTaetN6YEojbHW+MAIYhUjQmX9dJ7Bgv+m9EF+gnNmEM9-aFnmAEzyAYzfQABWDFuLsURpIl6gzABCTTy8AA+cX9BRfs2gRz3azCIqYCiwgWNfW1s+voIYKW0uAt7Uc1uItEmQdScp1pqmsmxcIPoFGVjZ26cqIutA040NvVlOCP4pd2gWq9VjTr3XhAhs2M0L17jnFdzm9s8bxsz0GCwD7SkGAwAasYzkfuyLdqSb5j4QDVgKm+LpHYAVdQnGL2XkYAeydkX5CtWts2CcrDi0lsrBQZgL66cbs3VOI6rJbDppXauUhbWlhPS1EZXUeogAGoFwagXhpyG4AQagooJqaCkDIZyIA9apZ6qgUaPAsBL0IOScgVB4jkB4CQYg25EB6DNv4ew5wApVx0BTrw1OAACA18BC+Zjzyn1PxpUANXOPAcBqDki02wA0rAgA) for @MynockSpit's example updated accordingly.

**Closed** 2018-06-08 23:19 UTC

**Comment by tokafew420** [comment] 2018-06-08 23:28
Thanks for the insight. I totally skimmed past that section. Lol
