### ISSUE TITLE
shouldNotUpdate throws an uncaught exception: vnode._state is undefined

### ISSUE THREAD

**Issue by barneycarroll** [MithrilJS/mithril.js#2067] opened 2018-01-07 17:16 UTC
When `shouldNotUpdate` attempts to query `typeof vnode._state.onbeforeupdate`, `vnode._state` evaluates to `undefined` and throws. 

It's unclear when `vnode._state` is set to this value - querying `_state` on the `vnode` in lifecycle methods always reveals an object.

I've tried to find the instances where `_state` is assigned to in Mithril source but in putting breakpoints at the moment `state` is assigned to `_state`, I can't find an instance where `state` is `undefined` before the exception occurs.

## Steps to Reproduce (for bugs)

https://barneycarroll.github.io/mle/

1. Use the `+` button in the `Node` element twice.
2. Observe the error: `Uncaught TypeError: Cannot read property 'onbeforeupdate' of undefined` (Chrome) or `TypeError: vnode._state is undefine` (Firefox)

## Your Environment

* Version used: 1.1.6
* Browser Name and version: Firefox 57.0.2 (64-bit), Chrome 63.0.3239.132 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Pro version 1709 build 16299.125
* Link to your project: https://github.com/barneycarroll/mle

**Comment by dontwork** [comment] 2018-01-07 17:23
I believe I had this issue when I had a stream.map inside oninit. That stream.map had an m.redraw call which was what caused the issue. Isaiah then got me to do promise.resolve.then(m.redraw). Don't know if it's relevant but thought I'd add it here

**Comment by barneycarroll** [comment] 2018-01-07 19:58
The app does play tricks with the redraw loop (part of the app is meant to draw in response to the draw loop of the other 😬) so something along those lines isn't beyond the realms of possibility. But — aren't the failure cases for lifecycle / redraw triggers either noop or infinite loop? I don't understand how things could get any more complicated than that from a Mithril internals perspective.

**Comment by pygy** [comment] 2018-01-07 20:53
@barneycarroll Are you mutating a `vnode.children` list somewhere in the hooks?

**Comment by barneycarroll** [comment] 2018-01-07 21:50
@pygy I'm relying on a state property of `children`… 🤔 ? It's exclusively within the Node component - I don't believe I've mis-referenced them. https://github.com/barneycarroll/mle/blob/master/Node.js#L21

**Comment by isiahmeadows** [comment] 2018-01-08 09:50
@barneycarroll `vnode.state.children` should have no effect.

By any chance, does this repro with `next`? ([link](https://rawgit.com/mithril.js/mithriljs/next/mithril.js)) I suspect it probably would, but given that the node in question is keyed and that @pygy has done quite a bit of work in area recently, things might have changed.

Also, you block *every* `m.redraw` call with a `requestAnimationFrame`, which should alleviate all concerns about recursive rendering. (The `m.render` algorithm isn't re-entrant, but your method is even safe with v2's `m.redraw.sync()`.)

-----

@pygy From digging through the debugger, it's erroring on [this node](https://github.com/barneycarroll/mle/blob/master/index.js#L46-L48) specifically, just not finding [the component's `onbeforeupdate`](https://github.com/barneycarroll/mle/blob/master/Node.js). No clue what could possibly be clearing `vnode._state`, though. (The only place in v1 where we explicitly clear it is [here](https://github.com/MithrilJS/mithril.js/blob/v1_1_x/render/render.js#L118), but that code path is correctly never hit.)

Found a lead, though, for v1 at least: [`vnode.instance` is receiving an empty `_state` here](https://github.com/MithrilJS/mithril.js/blob/v1_1_x/render/render.js#L324) (for obvious reasons), but on the second iteration, `vnode.instance` is set to the node itself somehow.

@barneycarroll Talk about obscure bugs...this is a torture cell... 😟 😄

**Comment by isiahmeadows** [comment] 2018-01-08 09:51
As for so far, I feel like I've not even scratched the surface at this point.

**Comment by isiahmeadows** [comment] 2018-08-28 11:13
`vnode._state` no longer exists, so closing.

**Comment by charlag** [comment] 2018-12-04 07:43
@isiahmeadows hi!
Does it makes sense for us to update? Is it stable for the production?

**Comment by barneycarroll** [comment] 2018-12-04 16:42
[Still reproducible with v2.](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAVwBdo4A6AKwQBoQBjAezUJibxgA8AHegJ0IAIGaOAKj0A5nH4BefsmQByBQF1lAHTQaO3PoMYj+Y8fxn8AFKUsj8YMAEoZAPn7ANJo2U744ACzPIAEQxmUjR6AHczOyp+S1JrW2U7DQBfDS0uXgEhAx4AQQAxUyinN340GHD+AAUeeiwIOBgzHhgAR3x4Qjy0CCxgiEYCnmwYOxAaJthaYn08AHZEAGYAVhAUqnRRvAA5egATGApqOkZmVkQQPp0BYCMY-IKU-jA6rH4FUgB6IhIFdIqmV0hzAGHwUFuZTiyDKJmAG1hH0YACMYGBeDB8Jx9sEYAoqIiFIwsTjmPjCSi0RjWlh6AA3PEEtAmExEtA0+mMsrKUitfb4WjNMxhQ4xHCEHwHBzSZxmVzMllxEUwJksuTiyX7ZRy-gAaxgAE9+CkHPK1e4JGZ9QaxTAJVLEWkFSbogCTIwIL1CDrrTERLjjabEUYrYaYmzPRBCApkpoFSZ-SE4PhkcqpLJkOpnUyyhg4Aa0LR+IxaK1cT6w-x9vVAy5g5bfUjC2WybHERhwhgo-xHlE3Szq1h4qX6FAoABJJj0ABqEEqcsRJlRPgwdMGPEQHzgtPoEvJ8cDZQRcZMa8qm4XB99iMIGHEqpZiZgm+A-GTqYO8GND5MwUIPDgF8exgWkGW-RF6CILxCAfE0nHMRdDAbSsFDPKozH9Pg7BjHMD3dKCiFMLAzEQ1lkBEA1YGkZFeEODd+AARk4dg31HCB9gAbn4TgMH2fZPXETdSBWECuP6HhxE9ISRKwZR91Ij49kOD4YmvE9zVZFT+w0jkwIAMj0-hiIUZEiEIRh8TrPDzU9CoeAACQAFQAWQAGU3BR2H3DS1RLKAIFoXVN10lUFJNXCfKMswFB8HgcO0813zTUh+k4MxQxtfgIGlRwFJMYjb3vKzIrVNSSpZEKLxyvLEpTZK4E4fzBTMCAYgY11rLVE0FI6hTjNMwhzLQSyzRK2yYAclz3I+ABqbySr8gKgvMarOtqj9Dk8bw-GtfgZo+UgFD28wks-MhYDQcQJWO9rY0i8LEN66yQ0bVC53Qlh9mwp6NMgwhoMRWMUgmEAphgGZBmEPAAAZlgY9ZNhATAcDwY4QaEc5CDwa4sn4JSYBeN4Dq+fH-l6LAbhce4kMkB5CmeV4a0+H5iCgOAyY0OkMB4F5oGYHnTCUDjOe5vQoHwLBhFMf9OmFtAuZ5kkA2lnhZYBIdaXwJgzGrWgJZYQhSF1-WmAAUVgHAmBiUa0LVKrSgPfqDgNEbEIo2BNwAAwUmj2AAWjgCAAC8BM3GieDov3fblyL+IaqAMANTcWTAWB2Bjnz0SYZPzVIAAOEC3wwYQA4miAwAzjTuED2Y0BzyB2BgTiFPCdiJRzlkGOh6GAFJK-NHwYAgcQfEIDvGO7vu+u5yS6-NaH+7VHi+NDtVhNEhTzM4ceWQXhTYDAMefL3tbOR4VOIhznx2MONBF5TtO-f41oIcYTcABJRsihhxclqQaoAPwfB-hLYaNUPJ1HCGTe699PY-nAtZYy5FCCURgNIVOHBNzQ0YvwFYvcuJnwvuEP2Sd+BgnMhxOS1sFKUnRK0JWzBk4lBlPwGqDDQrqQ0nmAsRZiTYnLHYL+Pl2GmFBGzGACUuGdm7L2Nsa18q8ibiMSId0fLHhoYWJqy1IrMOcGw-hzAVadHgSYY8kViL42ofIvUhoPIMWgWojqGkfrmiQe7NBcdGqJ03Bg9OLw06bgYjgvBfd-EcCfhAF+tdNwgMllQvq0UE6oigK7ax7ivY1TVJ4hOpDfFcUySyZe-FLrSQ3tYtUyIMCBXEHULW+xNz+RHoQGphp74aTgTVYghAPb8G9uUlkMBxCkA+IxNQahSAACYRmtzHMWNAUAjS+AiDTKQrQE7EEuvwcy5RPyMUmTEAprJGAhSOjMqAcyFlvklFUe0TQVkxDtLQApntFFeOal8Eiag4B2Bml8IqCh372KcWokxrjooNWLpZBQrkJC8whBNcwAAlQZpsuB2EQPFThPkhwyxENFPSaBkQNQ4pimqxlPTQWQag9BAScFBOhlQ4q5V+Bc3Fs+OF-NQW-V6GgaCm4CYykORyhFsgji3gknaUgrLjE1QemtFxGljKcFaKk8q6TekFN8TvOlE98EFMIWIYhpDyH0Daa4meUl55moqVU3UNTIJoHqfwZECdArWpZD-XgO9wjX2YO6jpa0zElWMreF1XJ+keCFSlDAaV-DEBwDEOIBseBzjgEkB2zKwUKH-KqzNiUUE9KEXmgcjQvG5L5gigy5hk2ptIJAR1Zhk1GhYSRfp5UKhVGReIVFaVIDwp4K811zQvhjLGX88Mo61AxjsKQZgeKm2qOLWqOwDggEmTEIFI6HkwgVBjEKrqEUl2-nzIWOZpYYDllfIOWsRal0di7AIWRkil2DmHHUMck5zKznnLeo9y5Vzrg8tuegu4fDzSPRUjd2jWSfXAxB7qbbzROiPUGo9IafBUqov+YuNdIaBOElIC9TQ-Z-UZb+vN3DT0lhbM0K9NY4LkeLa+9xpBPU81kAoPkHNEORXvTIwofYsUQarPUeIBajhscFi0l2+6kOydMVyvN8aOHyZZEdBxR7gVHtUzW+A0a0pNvgqp-K0VCD7Esk28MHxF1Lq03muzkUHPmicyYBVWbMMeNLTknxacuJFNXuvLAXFKnVNqY6hpw9R7ScoXBxV0UBpDVzeVcak03IeVoLAbmsWfKLUCiYe2grEMeHiI1AKzRoYxEnPWqMBoXMsjlWS+LZkLJWMzSlpyaWPjIjLLqbL3KMtLXyytDNeaQxKHDAAKim5i8qDXrH9Wa8NVrzL2tTQ8rwOcTABgtf1Zowb-ACu5UQ7EqWsgACEJ24CKdMW5uLJlFtJbGmgOyHXpoKDCPQTgwF9jKL6+aXLuohu6KFSI2QMsOGzZs8u0FdmOomhBmDV+UNLiwwmQAFnWMoGg-k0C6gQCgLYKNLgNAlCmqAAABQEWMaD4B4FAPAo9-qAS+D8XldrWP1C+CT2K0BycTNINDAXfseC0FIAxLnUYedQDRjQFBnBcCXDgKWCAnAsYpGUCkIAA)

**Comment by isiahmeadows** [comment] 2018-12-20 05:02
@barneycarroll Could you come up with an automated repro that doesn't require individual clicks? Something that only requires `m.render` so it's a little easier to trace?

**Comment by pygy** [comment] 2018-12-20 22:57
[got it](https://flems.io/#0=N4IgtglgJlA2CmIBcBWAnAOhQDgDQgGd4EBjAF3imRAAsyyAHApAehYFcA7BgawHMMJAPZgWkMjQBOEWAAEATBgAMygLSSSGAIxiIE6bAwArAiHwAzGfFNIA2qE4BDMIiQhjp-MM4Uf1bwRkAASc8AAeZAAqECQ8QQC8QeYJAHxBAAqSIhBEGJLWQrAAbvAAFACUGBLwnKXm5QA6nE1FjpJB7AxQjhRBCUFkkuzwANxNTQjBnd0UAMJCXMGJSuPNawHBJGAM-cBNfUUQ8ADuSEEVqXucfX0BhfAYsEJ8pQ0ghydvuB1dPfCN1xu+TI7Ek11s+xufTAGHMkkcfBcPlKwCEnBI+T+FWAdwQj2erxAqmJqiCDCEgVUH2OQQARvBzEJ8kESao3uUAL7fNHTLHAHqDAgc8r8+iSAgYNEY+BYzlc2wAXXKuEhULApQA5FAIEUNd8rlCoWj6Yz8ryKGdzuVUkFVYa+ub4Cq1va+jzfhRsXb7Y7+uZHLAiKtXTdQhForFShV4ikDSGbriHk8Xm8+NIIOzva78pwoPBJBd430s1DhSWglzg66pbAYjxLa6LjHbYCQ77EoNhs77ZXW4aIX37eqtTq9UE40Wa3Xsb2i27OI7sYn8S8ANSrx3zRac8t9Lm2kCzWuxAbHGLwTODm4K7uG5VZmFwhFIsgoqWYz0i5fJwmsskUsgqSOGlHHMCh2lZdl93dGYylFQVhXg8VJXRD8yjlXBFXvF1r0hXsOVWDYgiyIQliCKAhBIdgXwwWkhCgABPVYWAAKlWJoiJzPN2kSJs0jjGEuPzUoSLIb51S2BhygBYtOAItYhILAFFIqJoiCiCAXAWV9FO+LQlCUAEmlYlgOLRQJiJqbj+kEyh4WOMYcJhMAFmRUTvkkgE2BYlgzEIYh4HICBzOofSkAAZiUEAORvEBa04HgbHsEAnBcahxCkGRZDDMg-NBWBqDoRhmDYLheAEYRRAygwFGUNQNG0XR9BkDw-LIBiGFcQgMQgBhcvwBgehIGhrGQWxxqUfAajICBQlgJoQBvWwtHwKEIGSUoik4eiHjIBEEkSBdYFga081pdg+D4fMFqWyaQAaMgHvW852sW3AtAANlwFB5HetAtHkPAtH+wGltsO7uVgKBpKCN7bFUFaQGBUFODhxGJ0NLadsEGgZCgHN+kKKAcbxnNyyxvMMFmwJHHReBCahqnOBpuny2RsEsw5OG7vGR6+ee0o3vkX6tE+3BwuFlBJol+QpbBu6yAAERiV8ATR1bDQFimHgosADpCdhjutb8CW1tXbvwB6rbIbW3rFj6ABZcAdj6PuwAB2Z3XY9hVYqIUgZpCtxRfd92kFFhGtFD8OPuihUOSAA).

When `shouldNotUpdate` is true, we should also copy the rest of the state of the old vnode (children, instance) on the new one.

**Comment by isiahmeadows** [comment] 2018-12-20 23:09
@pygy That might do it. I for some dumb reason thought we kept the previous subtree, or I would've caught it and fixed it years ago. 😄

Can't wait until I can review your eventual PR for this. 🙂 👍

**Comment by pygy** [comment] 2018-12-20 23:45
Actually, we already copy `dom`, `domsize` and `instance` in `shouldNotUpdate()`. We should add `text` and `children` for completeness. The old attrs should also be copied.

[tentative test cases](https://flems.io/#0=N4IgtglgJlA2CmIBcBWAnAOhQDgDQgDMIEBnZAbVADsBDMRJEDAKzPwGMB7KgF3l+QgAOlS5USPAAQAnflHjTJAXklgMsqvOkiRnDACN4BTrICiNdgAsAFAQCuonhG7WAlMBGSondnfq8DTigATwwIKioFAAkAFQBZABllSSEQAB4oCAA3SWglaU5OHgA+NIB6TKzi1JEAX1cdKk5rVO5DaWNZOwAHKBo+GXgeO2kqcIBzSQIaWBJ4SS5uiHgSSR5Lec5YKAXLYigNVNwph3YnF3dPSSyaRSym+WSwFpBKo8lgWuPyZ9S3kFcAF0GlRJNdbpIen0+DsVL9Xtl3sA2kYTPAof14EgTo5nFQ3MBZMNRlMZnNal9JD8XjRUkCQVcNFprAUisd7kF4CCwUyFCzCjxjhiYdyUqDJM1hfAoBgrPsNOQAAyAjA8GjjVwYeAARzsZJe-xB9UazVaVHanXRvUxg2JYyok2ms3mi2Wq3Wm22a3gAA8eO97LiLh5xTc7g95nCDYiQMdPt9UkRpBJUsCrmHIdaYU9o1kkSjLVLsYGzniCUSRqCneTjVRGXI+azBdcI6LedJ+WzM9DpaKrpKs9KMP0eMmMAW0VLNTq9bNrA55ERIlAjQymi8UR1J4PbZWJqTnQtOEsVmsNhKvSPpBB9HY+CQA6dzvjLqGIRzHlG-jG47WwRmpVhVRc3zc1US6QdiyfMt3ArElq3gCkExAQDUzXHkGw7Jt2VbetNEbAUhUHFcrn7ediNVX0eGnXV9UTCBk39AE6jXPRpAcNxGljEA5gQUtuDIRgACYABZUAARhAWpAXwWBwgAa0EygQFoehBEgdZr1gAABSI-W4kZYEESweB4boSCQMoygcbp5PGWVODAMoNMsLTtKEjBFU8gBaaR2AwcTnIgTTiBYNgQB4YJugYHj2GvboeG47p+isFYKHIJV8H4JxIlgEQQBk8hxPwMEwQgAhJGsD94FVdVlBUKg7FgWBXC8eBb3GcYFHywrFXwIR-ScCrrEigrcHEgA2XAUCE8a0HEoS8HE+bFsKzLYwvFdWrG8hvOKkA4KoHb9pDUqzskKyW05WU9m2DRki2GU5Tu-grnOi6yiu+QwnENVREjTafokGh-re87DrBsFah2vrhDrQaBvKyqxqE2aFtmgBmVGUD6rGhJxtbYZ4AARCAzk4o7Cv296kaqiMMG8MB6skRrmtasQSC2GrYE4cY6c5EEYf6hGeGqsbJtwCaRNwESJomtAMZluWFcBGSePgPjn0EkBsCExUkHE8TvN1oSkEVKTcGoOgYs4EhovYAzpCMxgTLMiyrJsuyHKc237e0jHPICspffgfzWG4yLosEEg4ogBKpMBWogA)

**Comment by pygy** [comment] 2018-12-20 23:49
Another option would be to drop support for `onbeforeupdate` as an attribute. I'm not very comfortable with messing with the attrs and children since they are user-provided...

**Comment by barneycarroll** [comment] 2018-12-20 23:55
@pygy we could loose `onbeforeupdate` without feature loss if we implement [`(before, after)`](https://github.com/MithrilJS/mithril.js/issues/2098)

**Comment by pygy** [comment] 2018-12-21 00:06
@barneycarroll Good point. That approach means that we keep "skip diff if `old === current`" though.

**Comment by isiahmeadows** [comment] 2018-12-22 04:55
@pygy If we drop `onbeforeupdate`, I'd rather us use a "don't update" sentinel we just take to mean "replace me with the previous subtree before sending it to any hooks, and don't call any hooks on it".

Alternatively, we could just have people return `vnode.instance` from `view` and add `view` as a magic attribute alternative to `vnode.children`. We'd just elevate `vnode.instance` to public status, documenting it as a readonly property holding the last rendered children of that DOM node/fragment/component instance. Personally, I like this method better, since it's easier to explain and still reasonably easy to implement.

But in either case, I'd rather not encourage people to memoize vnode instances on their own. Mithril's allowed to as it owns them and controls them, but users are not since they [*give*](https://doc.rust-lang.org/stable/book/ch04-01-what-is-ownership.html) their vnodes to Mithril - they don't just [*lend*](https://doc.rust-lang.org/stable/book/ch04-02-references-and-borrowing.html) them like they do in React and similar. (Unlike JS or even TS, [Rust provides types to verify this](https://bryce.fisher-fleig.org/blog/strategies-for-returning-references-in-rust/index.html), but because this is in JS, we have to rely on conventions for it.)

**Comment by isiahmeadows** [comment] 2018-12-22 04:55
But in either case, this really needs fixed in v1 and v2.

**Comment by charlag** [comment] 2018-12-22 08:08
What other type enforcement other than "readonly instance" on the vnode given to view we need?

**Comment by isiahmeadows** [comment] 2019-05-15 13:20
Note to self for later: find time to get [the fix](https://github.com/MithrilJS/mithril.js/issues/2067#issuecomment-449162547) implemented and landed in the main branch. Not an explicit v2 blocker, but it's something I want to get in ASAP.

**Comment by isiahmeadows** [comment] 2019-07-03 08:38
Reduced the issue to three variants, one missed in the initial investigation: [1](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaETAVwBcIAlReCTQlAM03jxOYEskZUBtUFEwBbZGgB0AKz4lIUCogWoQIiQCcl+ROoAU+CGDJiFEgEYR8ATyIACfgB0ot2yN0ByfFwBu7u8GgzRGYITTJsfExFFFtmMigwCi5oW10ASltgW00KMnVnCnUyRFsAX1K7R2cXVw8vXzSnFwBdNKInVqc1TShtPQMjEwpzSxt7JtrPHz9MwODQxHDI6Nj4xOTndMzsxFz82LY8Morx6pc3KYaJ1vaoTqhurR19Q2MlYYtrSomL+pmAqBBEJhCJRRAxOIJJIpLZZHJ5ApFErlb5nSZ-Sq-aZpe4tNodNLEdAibA8HSoKBkeDwEh4JDraB8NAARgADCgAEwAVhApWaJHgXCgAGsmYIQMIxCoRFwKAALdQ8aSyEB5eAqOUUCi4FAAel18WwwoA5hJICJdTL5Yr4AABDkSVmOgC06jAEgAbJbZQqlTIiRQrNhxCAYGBFdgKLzmqUgA) [2](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaETAVwBcIAlReCTQlAM03jxOYEskZUBtUFEwBbZGgB0AKz4lIUCogWoQIiQCcl+ROoAU+CGDJiFEgEYR8ATyIACfgB0ot2yN0ByfFwBu7u8GgzRGYITTJsfExFFFtmMigwCi5oW10ASltgW00KMnVnCnUyRFsAX1K7R2cXVw8vXzSnFwBdNKInVqc1TShtPQMjEwpzSxt7JtrPHz9MwODQxHDI6Nj4xOTndMzsxFz82LY8Morx6pc3KYaJ1vaoTqhurR19Q2MlYYtrSomL+pmAqBBEJhCJRRAxOIJJIpLZZHJ5ApFErlb5nSZ-Sq-aZpe4tNodNLEdAibA8HSoKBkeDwEh4JDraB8NAARgADCgAEwAVhApWaJHgXCgAGsmYIQMIxCoRFwKAALdQ8aSyEB5eAqOUUCi4FAAel18WwwoA5hJICJdTL5Yr4AABDkSVmOgC06jAEgAbJbZQqlTIiRQrNhxCAYGBFdgKLzmqUgA) [3](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoArakyKAF0T6oQjVgCcB+RKIAU+CGACuzPqwBGEfAE8iAAhoAdKDp3BemAOYodAcnzkAbtd2ZevUTCvB9IfC8wBaFzdvK29SCAhvXWhVRHDxBWxffitSBSgwXnJoHWkAShMdcV4FUSM3BUQdAF9q3TAAC0p8cSgrGgBdOsMOvMMRVskZOUVlXjUNbT1DY1MLK1sHJx0g909vZIDVkJ1vVUxRKJ0YuIgEpJdEVPTM7KN8wuLSo1JMeDwaup1G5tb2rqIPT6UAGEiksnkSgE43UWl0BiMJjMlhsdkczlcaxMGz8gUxOz2ByOJ3iiESySuOjSGSyOQewCKiBKZR0FSqtXqTXgLQE-26UF6hh4cCQrHgEHMENG0ImWlYFHcvAAwlz8KxzEyAIKY8iqBT8aQ4sx44IgPJ5YjoRjYShSVBQBTweAkPBIW7QahoAAcKAATCBqh0SPByFAANaeuggBjMISMci8BqiSgcLggUrwIQNVy4FAAejz6WwYfMrEgjDz8cTyfgAAFfawAAxN-yiMCsABslYTSZTnEtvE02BYIBgYGT2F4Aa6QA)

When you go to view it, open the browser console. Flems just unhelpfully shows "Script error". The first one results in an error like that of this bug. The second results in a DOM node going mysteriously missing. The third prints a wrong attribute value. All three have a nearly identical root cause.

Stepping through each variant, it's not as simple as [@pygy's initial suggested fix](https://github.com/MithrilJS/mithril.js/issues/2067#issuecomment-449162547) made it seem, but [his follow-up](https://github.com/MithrilJS/mithril.js/issues/2067#issuecomment-449178876) is almost there. What's happening is that somehow the old vnodes that Mithril has are getting crossed up with data that's never used. So what I'm getting is this:

- Previous attributes need retained for proper attribute diffing.
- Previous children + text need retained for proper children diffing.

It may have seemed like `vnode.state` wasn't being set appropriately, but it's already been set prior to even entering that invocation, so that's not the issue.

Fix finally incoming!

**Closed** 2019-07-03 08:53 UTC
Labels: bug
