### ISSUE TITLE
using key in attrs causes onupdate. Expected oninit

### ISSUE THREAD

**Issue by MarcWeber** [MithrilJS/mithril.js#2650] opened 2020-12-31 13:19 UTC
dev or stable mithril: https://mawercer.de/tmp/tmp/mithriltest.html
```
              'key': attrs.type,
```
I do set key, yet onupdate is called. Why ?
If I change :type to :key also replacing attrs.type by attrs.key then oninit gets called.

Setting a different key shouldn't it cause recreating the component ?

So what am I missing ?

**Comment by cavemansspa** [comment] 2020-12-31 18:57
hello marc, i ported your [example to flems](https://flems.io/#0=N4IgtglgJlA2CmIBcAOADAOjQNgDQgDMIEBnZAbVADsBDMRJEDACwBcxYR8BjAeytbwByEAB4oEAG4ACaAF4AOiD4ChrJQD4FVadO2iA9BMkauIEvATdWEfmUZokAThABfXNToMmAKzI9+QWFGFRJWaRpYWAB9VgBPAAd4Emk5aXIlGhgAJ2SSJVw9EABzbN4AVwSC6QByPjAEmio4msKapOySflbalVZsmmsemqhebnL6AWGAIwhabJaAXW1tUPCAYWiIQTBoqngAd1TpYG1dXX457aRpAApgGlZ+klcASlSNE7Pzn9DeBAwsF4xVuSn4sio22qj2erwA3N9dO5EdJ+JUoI94Dd7jDOm8Pl8dD9zn8AUCQWCdNxmE1ivBoU9OvCUciibpJBBDtiHoyXu85J9TmziblWOVsjowKCQMZqkpNtt4Lt9gdqgApADKAHkAHIYMLZObFCAEOK3XEkV6vFnaVwrKhraSbACyQnKAEEqFB1oE1MchSiOVy7sAwpjChbCtTiFBclR8QLCcSSXZwpNytE+moUmlyMthT9ReLJdLZVwUcndFKlMYMOmGc8MGVyoISNEmlBoumMERYIJsrdbgAPfmfIcsXIEV51mgJQcjj4Vys-asyqR1t2KsDVKVgJsVQQYAAycwA1oVgDVmJOajdx9f4AR3NJ75PYtsEFal8mrbhv8TV1rLMBB3W4rwARh6C0MBsVhPyjZgYzja0C3OFCfjteN7UdZtW3bL0uzdY4MmFIVlyvN9YIQW9amYXh6Faf8KMfGiagMOiGL-VDdFwrETmYcD3zgvjblHWj6PgYZeNY9iJOGSQqF4KBJJuYAgwObExMAqQ5RAAB1YhYFPejJiUV5XEwjCuJ+MjK141T-x+CChOozSCQAAxVaQABJgD3XiMEaAYpRqeIkhqcz3Os5dziUXilBuJQDC3AwVQMJAwvpctuOJJQFKUrKHJy5d1O5C0E0FRyYt0Ul4EBYFpVPeA4lkfIuAiXkYMSeBmWK6rpCLCVpClBUdj2Q4Lyq-rzlC7qaOgzLoum6qaialobgW7qluW5cDAMaRojscpuG4PJsS3MTbJ23b9pXfcWzqixWDA5KdgMeAJFYdLoB6S8fpubh9WiIFuEiDBBgwaBbgut4puWvbpEs66MPQ66keq9HiUx1l820AheGyO4EHCcJeAICIolibrLSTc5eLbDtCKocpAvKEhmHuB8CBcvjPMOHzgFYVwotom8bnc16lVSw4DF8oX3NhrCqHtBGsigYa3TxgmifgcIIFRcn6fwzt03eK7pEdIdjggFETTucdeLN-8HYPOr8uU45B0kMT7jh0qQ3Ky64cLXXi2G24XTdT1vV9ARJr66qjcZ9MbiTgj0225GqL4l2HpYQTs9E4PzmfKVJAjXkrQRBPEf-N5XmHe7D3dnqbSV7QEaeyppAAVQASVWVMBtdnMTkw+18cJ25idkA3h4ehn07dJ3hTt6Gm56+fW3ICAN43xZrb3lvbXtfzXduUZxkmVgMDpVgAFEEGvgAhOI+6gMDgNYCLCiSjissKPTFCZh6gJGIPAbIIhpg0GmJYMwFgrA2DsCIbAAAmJAqCAAsbgPAgFoPQEQGBuAkH8MoWOrARBuEWPgWAZ57CUDwV4EQkBWDXmIGYcUnBGBsFYAkEgSA9rlCoAkU8xQiH0QMCwthsAAACqCsAYEwZI7Y0i6xzAwH4MwmURAkG4IaBIFDXCLFcEAA) so that it's easier to collaborate.

i believe part of the issue is stemming from memoizing vnodes at line 417-429 which results in no vdom diffs.

check out @osban [re-initializing examples](https://github.com/osban/mithril-codex/blob/master/how2code.md)

you can probably benefit to moving to using route-resolvers with your routing.

**Comment by osban** [comment] 2020-12-31 20:49
@MarcWeber I agree with @cavemansspa's assessment. If you'd use a route resolver, you could use a Layout, and do something like [this](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAIoGAJ60ArlIC8kgBQBKScoB8k4AB00kyeKnFZAB3jbJyAOQYAJk4BO8OPYqT7Ac1eKll4+dFiWGGiywfbWrnD00ULErhjUxNFOtNQKOAzRAEYQmK5RALpGJhWS7sQKrsaGxiaSAG4QMADuiOrAGMTJcN7UhNBuTKxaulXNklhqBiBOEC0LFNMzs-OLy-i5CqvrG5IW1nC7GJZqagAeFBCTOodHmwtLLbtMChCMWAdNzxsAIQQJ4AgD8myw+ACShg+AAMkUANbeYCEdxgboAAwA9IRaDgsexJFj8YSNKDnt05lCYYwEcjUeiYJiSTjvjAsDi0J0cQASYDXVhE7xYnkdSQCoVYin-AGSWXyhWUjRrOUzOavHZJER-JVzeyEACMwT6A3wxG+sFVlJMw1G7jQKqeiuarCM7qdaDMkjJMFswDanW6mm0ek12xWlEkCwA6tAoEiCbkFhpPUYfeKOVgA1V6EVviYQ71+nEJmHTPR4rB8FBaL4tvm0N9VpIzXEbU16ApLE4+jBi+24OXdJW0NW4XWGwtu73+62h52TEGJc1B6Xhw8XpHWwssz9uq2AFIAZQA8gA5fASVxFXwQMCyNSL2XptC0xSMNSZbK5Yj4fJaCcWRvHsPECRgYJGhMMC-XsbpoOaR0nBgVwQy3OYZHkJRUUtYhYG6Q0IPsYk5j9DRXXYKowOzbleUQE5IIQ9ZkNQ9CK0wuRP1wq0BxJcVJWAD9YXwcIUgNRj7DTEVNn3TlUSRGBZGpaFPzhMTsDUexJLTCiqk9CYjEoGgCUsaBULwfIMHyGByCoOBbJgNIICrPAAGYAE5EAABjYDgQEwHA8Hwag4AEEzhGYHg2FKKgoGRBAUE4IKeCwb50WgYy6nIHgSGISw4EQHEcQUNBLCRXwQoJHE0uIDKoAAAQAJnwbz8AAFhq9LbygXYinwfhjMYvA4GoW9LFEVhSlYIA).

**Comment by MarcWeber** [comment] 2021-01-01 11:49
@cavemansspa Thing I don't get is: The :component passing different key to new component could have state. So why does using key on the the parent components make it work ? I mean I could be setting state and m.redraw, right ? The logging (on update) does show that the changed attrs get passed. What are plans for SSR?

Example is here: [fleem](https://flems.io/#0=N4IgtglgJlA2CmIBcAOADAOjQNgDQgGcBjAJwHtZZkBtNXARjQBYBdfAMwgQJtADsAhmERIQGABYAXMFXxEyfSfEXIQAHigQAbgAJoAXgA6IeYuWTjAPkN8dOm2oD0mrZZD4C8BEUkQFPUTQkAE4QAF9cfiERMQArHjkFJRVRUwJJHQFKAH1JAE8AB3gCHX0damMBGBJigmNcexAAc3IAVwL6nQByeTACgT48roauopICBWHu00kSAR8prqgyIlbhRUWAIwhBEiGWGxs0jIBhbIglMGy+eAB3Up1gGzs7BR2LpB0ACmABSVmCGEAJSlSyPZ4vSFpCjwDCwMhNL7GBR6PgXTp-AFAgDcELsETxOgU7Sgf3gnx+mPGwNB4NskJe0IQcIRSJAKKI4gGTXgGP+4xxhIJ9LsWggdwpv35gJB+jBTxFDJqklaJFsYDZLk6xjOF3gVxut06ACkAMoAeQAchh0iQdk0IOw8l8qQQgUChTYwoc+McdGcALLKVoAQT4UBOSXMDwVhLFEu+wHSZIaroanK4UBqfBpcrpDMZ-gy61a2Rm5hKZWoB0VkOVqvVmu09UJBbsGuMLgwJb5AIwbSUBGyAyg2RLGE4sCUJC+XwAHrKwXOJDV2EDuwICrOF6DW23IR2QF2S3qwJ0NWB+2RWkoMAAZHYAawawC64lXXU+y-f8HYER036rrkFwIO6e4Fu6uDgQyh5duWijnl8b70FMroYL4kigem4iZtmHq1i8+GQt6OY+ggGSPvAeTZPoaC4nwRxFjoNxzpI2SUXkDxfIu+Y6Bx2QANQCRC9ZqpkOT5EUBDUPxOgAKTibAuSFMUcLKE0kjiCw9EkTYniSAAkmYJBaFks48cAOhMrC8KIl0NRZgItz2l0OI6JeDlzLc3HYjoYQ6A0jBoGgOiCgxvpMQOxTDuGY7Bg8FSKgq+5vkBGEIJ+3TiGQwjDNBqW-plXSONluVQQRdhRZ8wDiPQwGYeS3w8W+OXwIsUVFSVrWLFofBkFAbXVfGtwUjxsHNu4jQAOpcLAj45esxhAmEJHEeVkLJW2VW8fudjIfVGWjbSAAGho6AAJMAHnXre-RzBqXSSW1y3Hetu12MYUXGJ8xiOKejiGo4SBPS2FUMsYvX9byyA7e9LzDZKrq5vK0Fw1Z-gwiyiLGBxeh1JNaFPWFaP7n6uNlCxbEcdxqNw9ZWNspTfFUXjjQNBxxMkwWomNrqlzXHcL601zj0qZlHFvVzKUceLVGS1LBaOI4OjZP4rREEQtQUqeFnCyTSswVeN6wvpSF-ZcjjwJokhA9AUyvnbnxEDa2TwkQWQYPMGDQF8OvAnraMG6tCsvP7YP7sH72Rwy0fCjWNjsGQJDfOROgZGQ7CKcpUkgptlU3dFI5xXwrQYAUrQEOIPw-uwB2NaddwXcAkhhK9WUfp8x3m-qAN3I4l0t8dYe6eFBtVFA7nBgnScp-AGQQESmdRUORclrnhJ+nODwQISjrfMuUXr2DB8FxgkMDVxXxaDxPx6wjiZI7r4dbXPDbuV8gbBmGEZRooQvP+9ZeMVRwlk+EA1ewZ5YK3So1E+xsJB1RgTTABMcGgai0KmaU7p6Jo2jsRd084ja3nPvAIiocvQ+gNvpdoOgACqBlGJ8HSDoZeMYR7T2Tl8VOC8M4sILivWKa9YZ719kQ0hfDjbSQgGIsRLBt4yJIRQ8K11jZfGWKsdYkgMA8kkAAUQQJogAQnkAyUAkLwUkK5Bov1SrQwaMvfC7gTA5QKFweAJBVCbAEJsLwTjPDeF8P4VQABmJgSAABMAB2cIkQQCCGEKoDARACAJGcWYFIIBwhsBALAJ8ARqBRASaISAmk7SyBAKqKgogpCSAKAQJAStWh8AKI+JoSScqOBKe+LgAABcJWAMBME6RcbpsBuw7AwPEJxT1VDEDtAUSQWSwhAA)

So I change the state (eg coud be stream/ var or like in this case a function).. I pass it as key.. Yet it results in onupdate ?
Shouldn't changing the key mean getting a new component ? I mean that's what its for ?

**Comment by cavemansspa** [comment] 2021-01-01 15:29
@MarcWeber -- [see doc](https://mithril.js.org/keys.html#single-child-keyed-fragments)

there's a subtlety where you need to wrap with `[]`.  that should resolve.

[original flem modified](https://flems.io/#0=N4IgtglgJlA2CmIBcAOADAOjQNgDQgDMIEBnZAbVADsBDMRJEDACwBcxYR8BjAeytbwByEAB4oEAG4ACaAF4AOiD4ChrJQD4FVadO2iA9BMkauIEvATdWEfmUZokAThABfXNToMmAKzI9+QWFGFRJWaRpYWAB9VgBPAAd4Emk5aXIlGhgAJ2SSJVw9EABzbN4AVwSC6QByPjAEmio4msKapOySflbalVZsmmsemqhebnL6AWGAIwhabJaAXW1tUPCAYWiIQTBoqngAd1TpYG1dXX457aRpAApgGlZ+klcASlSNE7Pzn9DeBAwsF4xVuSn4sio22qj2erwA3N9dO5EdJ+JUoI94Dd7jDOm8Pl8dD9zn8AUCQWCdNxmE1ivBoU9OvCUciibpJBBDtiHoyXu85J9TmziblWOVsjowKCQMZqkpNtt4Lt9gdqgApADKAHkAHIYMLZObFCAEOK3XEkV6vFnaVwrKhraSbACyQnKAEEqFB1oE1MchSiOVy7sAwpjChbCtTiFBclR8QLCcSSXZwpNytE+moUmlyMthT9ReLJdLZVwUcndFKlMYMOmGc8MGVyoISNEmlBoumMERYIJsrdbgAPfmfIcsXIEV51mgJQcjj4Vys-asyqR1t2KsDVKVgJsVQQYAAycwA1oVgDVmJOajdx9f4AR3NJ75PYtsEFal8mrbhv8TV1rLMBB3W4rwARh6C0MBsVhPyjZgYzja0C3OFCfjteN7UdZtW3bL0uzdY4MmFIVlyvN9YIQW9amYXh6Faf8KMfGiagMOiGL-VDdFwrETmYcD3zgvjblHWj6PgYZeNY9iJOGSQqF4KBJJuYAgwObExMAqQ5RAAB1YhYFPejJiUV5XEwjCuJ+MjK141T-x+CChOozSCQAAxVaQABJgD3XiMEaAYpRqeIkhqcz3Os5dziUXilBuJQDC3AwVQMJAwvpctuOJJQFKUrKHJy5d1O5C0E0FRyYt0Ul4EBYFpVPeA4lkfIuAiXkYMSeBmWK6rpCLCV0ilBUdj2Q4Lyq-rzlC7qaOgzLoum6qaialobgW7qluW5cDAMaRojscpuG4PJsS3MTbJ23b9pXfcWzqixWDA5KdgMeAJFYdLoB6S8fpubh9WiIFuEiDBBgwaBbgut4puWvbpEs66MNefNkaR6qMeJLHWXzbQCF4bI7gQcJwl4AgIiiWJustJNzl4tsO0IqhykC8oSGYe4HwIFy+M8w4fOAVhXCi2ibxudzXqVVLDgMXzhfc2GsKoe0EayKBpHrKgCaJ24SdkVEKYZ-DO3Td4rukR0h2OCAURNO5x1483-0dg86vy5TjkHSQxPuOHSpDcrLrhwt4DFIaRuiV0Wc9b1fQESa+uq42mfTG4U4I9NtuRqi+Ndh6WEE3PRJD85nylSQI15K0ESTxH-zeV5h3uw8PZ6m1le0BGnsqaQAFUAElVlTAa3ZzE5MPtHXibDg3ydHh7Gczt1neFe3oZbnqF9bcgIE3zfFht-e29te1-Ld25RnGSZWAwOlWAAUQQG+ACE4gHqAwOA1gIsKJKOKyoUBmKEzD1ASMQeA2QRDTBoNMSwZgLBWBsHYEQAAWbASAABMABmNwHgQC0HoCIDA3ASD+GUPHVgIg3CLHwLAM89hKAEK8CISArBrzEDMOKTgjA2CsASCQJAe1yhUASKeYoJD6IGDYRw2AAABTBWAMCoOkdsWRdY5gYD8GYTKIgSDcENAkKhrhFiuCAA)

**Comment by MarcWeber** [comment] 2021-01-01 18:52
Ok - thank you very much. Still looks too complicated to me. The documentation could be more clear by making the array parentheses red or so if they are the most important thing which doesn't make sense to me at all. For me [x] or x was the same. My brain doesn't want to accept this. I have seen that example in docs but totally (intentionally) missed the array cause doesn't make sense to me.

My original case is solved. But I personally tend to see it as bug violating KISS principle which mean keep it stupid simple. Mithril gets much right though. Up to you whether you want to close this or not.

**Comment by pygy** [comment] 2021-01-16 13:06
@MarcWeber this is related to #2654 

Keys are only detected in child lists, not in the vnodes returned by components. If you [wrap](https://flems.io/#0=N4IgtglgJlA2CmIBcAOADAOjQNgDQgDMIEBnZAbVADsBDMRJEDACwBcxYR8BjAeytbwByEAB4oEAG4ACaAF4AOiD4ChrJQD4FVadO2iA9BMkauIEvATdWEfmUZokAThABfXNToMmAKzI9+QWFGFRJWaRpYWAB9VgBPAAd4Emk5aXIlGhgAJ2SSJVw9EABzbN4AVwSC6QByPjAEmio4msKapOySflbalVZsmmsemqhebnL6AWGAIwhabJaAXW1tUPCAYWiIQTBoqngAd1TpYG1dXX457aRpAApgGlZ+klcASlSNE7Pzn9DeBAwsF4xVuSn4sio22qj2erwA3N9dO5EdJ+JUoI94Dd7jDOm8Pl8dD9zn8AUCQWCdNxmE1ivBoU9OvCUciibpJBBDtiHoyXu85J9TmziblWOVsjowKCQMZqkpNtt4Lt9gdqgApADKAHkAHIYMLZObFCAEOK3XEkV6vFnaVwrKhraSbACyQnKAEEqFB1oE1MchSiOVy7sAwpjChbCtTiFBclR8QLCcSSXZwpNytE+moUmlyMthT9ReLJdLZVwUcndFKlMYMOmGc8MGVyoISNEmlBoumMERYIJsrdbgAPfmfIcsXIEV51mgJQcjj4Vys-asyqR1t2KsDVKVgJsVQQYAAycwA1oVgDVmJOajdx9f4AR3NJ75PYtsEFal8mrbhv8TV1rLMBB3W4rwARh6C0MBsVhPyjZgYzja0C3OFCfjteN7UdZtW3bL0uzdY4MmFIVlyvN9YIQW9amYXh6Faf8KMfGiagMOiGL-VDdFwrETmYcD3zgvjblHWj6PgYZeNY9iJOGSQqF4KBJJuYAgwObExMAqQ5RAAB1YhYFPejJiUV5XEwjCuJ+MjK141T-x+CChOozSCQAAxVaQABJgD3XiMEaAYpRqeIkhqcz3Os5dziUXilBuJQDC3AwVQMJAwvpctuOJJQFKUrKHJy5d1O5C0E0FRyYt0Ul4EBYFpVPeA4lkfIuAiXkYMSeBmWK6rpCLCV0ilBUdj2Q4Lyq-rzlC7qaOgzLoum6qaialobgW7qluW5cDAMaRojscpuG4PJsS3MTbJ23b9pXfcWzqixWDA5KdgMeAJFYdLoB6S8fpubh9WiIFuEiDBBgwaBbgut4puWvbpEs66MNefNkaR6qMeJLHWXzbQCF4bI7gQcJwl4AgIiiWJustJNzl4tsO0IqhykC8oSGYe4HwIFy+M8w4fOAVhXCi2ibxudzXqVVLDgMXzhfc2GsKoe0EayKBpHrKgCaJ24SdkVEKYZ-DO3Td4rukR0h2OCAURNO5x1483-0dg86vy5TjkHSQxPuOHSpDcrLrhwt4DFIaRuiV0Wc9b1fQESa+uq42mfTG4U4I9NtuRqi+Ndh6WEE3PRJD85nylSQI15K0ESTxH-zeV5h3uw8PZ6m1le0BGnsqaQAFUAElVlTAa3ZzE5MPtHXibDg3ydHh7Gczt1neFe3oZbnqF9bcgIE3zfFht-e29te1-Ld25RnGSZWAwOlWAAUQQG+ACE4gHqAwOA1gIsKJKOKyoUBmKEzD1ASMQeA2QRDTBoNMSwZgLBWBsHYEQAAWRwAAmFAABaVB2AkAYIwW4DwIBaD0BEBgbgJB-DKHjqwEQbhFj4FgGeewlBSFeBEJAVg15iBmHFJwRgbBWAJBIEgPa5QqAJFPMUSh9EDDcN4bAAAAhgrAGBUEKO2EouscwMB+DMJlEQJBuCGgSPQ1wixXBAA) the vnode  in an array, Mithril treats it as the child of a keyed fragment and it is re-initialized as you wish.

Going from 

```JS
return m(C_item_new, {
  'type': attrs.type,
  'key': attrs.type
})
```

to

```JS
return [
  m(C_item_new, {
    'type': attrs.type,
    'key': attrs.type
  })
]
```

**Comment by barneycarroll** [comment] 2021-04-15 10:29
☝️

**Closed by barneycarroll** 2021-04-15 10:29 UTC
Labels: Type: Question
