### ISSUE TITLE
Custom Elements Everywhere compliance

### ISSUE THREAD

**Issue by porsager** [MithrilJS/mithril.js#2220] opened 2018-08-30 09:21 UTC
I've made mithril ready to be added to https://custom-elements-everywhere.com here: https://github.com/porsager/custom-elements-everywhere/tree/mithril ..

It passes all basic tests, and it doesn't need much to pass all advanced tests too..

What's missing is:
- Set arrays as property if added in attrs
- Set objects as property if added in attrs

I think all of these should be fairly easy to add support for if we want to. The only one I'm unsure of is the first one which serializes to a comma seperated string, which someone might rely on? (breaking change).

Should we consider including these for v2? If so I could try to make a PR fixing these things.

**Comment by isiahmeadows** [comment] 2018-08-30 09:37
Let me address our status for each of thise:

- Set arrays as property if added in attrs
- Set objects as property if added in attrs

Are you referring to an own property, and not an actual `getAttribute`/`setAttribute` call?

- Support kebab-case custom events in attrs
- Support camelCase custom events in attrs
- Support CAPSCase custom events in attrs
- Support PascalCase custom events in attrs

These are already basically done, if you're referring to anything event listener related. Mithril has never specified anything other than a basic `on` prefix since at least as far back as v0.2 - I've leveraged this to use Bootstrap's custom event system personally for a number of projects.

If you're referring to `onfoo` event listener attributes or `elem.onfoo` properties, we don't even support that for the DOM unless you use `vnode.dom` directly. I recall ripping that out of v2 (needs backported) for performance reasons, and most other frameworks are similar, at least those with some degree of maturity to them.

**Comment by porsager** [comment] 2018-08-30 10:10
Thanks a lot @isiahmeadows 

I've found errors in my tests for the event handling, and all tests are now passing (removed above for clarity)..

So now this is only about the arrays / objects being set as properties on the element instead of attributes.

**Comment by isiahmeadows** [comment] 2018-08-30 10:59
Found the cause: [this condition, which handles properties, specifically *excludes* custom elements' properties](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L690) from the magic inference semantics. I don't think a special case here would take that much code, and I don't think we'd break anyone fixing that. If anything, the fact we send everything to attributes for custom elements and not normal ones would be surprising to some consumers, especially those who don't have as well-behaved elements (some have a habit of not using attributes as fully/mostly synonymous to properties).

**Comment by porsager** [comment] 2018-08-30 11:02
Ah, that's great @isiahmeadows ! I'd also be surprised if anyone relied on that..

**Comment by isiahmeadows** [comment] 2018-09-01 01:08
FWIW, we don't document anything special for custom elements, so it'd be reasonable for a user to expect that we *would* at least try to use properties before methods on them, too. A user would probably read our docs, try a custom element, and be surprised to find it doesn't work how they expected.

----

I tried removing the check for custom elements, and found nothing changed... 😟 I'm looking to fix that in an upcoming PR (that also includes the bug fix).

**Comment by isiahmeadows** [comment] 2018-09-01 05:27
@porsager The attribute issues are being addressed in #2221. It was a pretty easy fix.

**Comment by barneycarroll** [comment] 2018-09-01 21:55
@porsager can you describe the value proposition in your own words?

**Comment by isiahmeadows** [comment] 2018-09-01 22:38
@barneycarroll [I think the value proposition should be a low bar considering the very small diff + behavioral change](https://github.com/MithrilJS/mithril.js/pull/2221/files#diff-000bdfae56251b0715111d2b18c9de3c).

As pointed out earlier, custom element support was untested, despite having clear behavior within the source. I see the value proposition as purely philosophical: we should just treat custom elements like any other element. This is what it tests for, and we were already 99% of the way there. It seemed arbitrary to limit custom elements to only attributes.

**Closed** 2018-09-20 19:08 UTC

**Comment by barneycarroll** [comment] 2021-05-04 09:07
I've submitted a PR to the Custom Elements Everywhere repo to reflect Mithril 2.0.4 passes all tests, with a description of our property v attribute assignment logic: https://github.com/webcomponents/custom-elements-everywhere/pull/1013
