### ISSUE TITLE
Component retains old event listener after its content changes

### ISSUE THREAD

**Issue by v4n** [MithrilJS/mithril.js#1613] opened 2017-02-10 07:27 UTC
I have the following component with a  `span` that should only call `unclick` when it's clicked but calls `click` and `unclick`.
```
function component() {
  if (...) {
    return <div>
      <div></div>
      <div onclick={click} class="click-me">
        Click me
      </div
    </div>
  }

  return <div>
    <div></div>
    <div class="unclick-me">
      <span onclick={unclick}>Unclick</span>
    </div>
  </div>
}

```

Here is a running example:
https://codepen.io/v4n/pen/bgQNGW?editors=0010

**Comment by tivac** [comment] 2017-02-10 08:13
Mithril redraws after the `unclick` function runs because of the `m.mount`, and it seems like that happens faster than the event can bubble. I verified in the chrome debugger that there's no stale click handler on the `.unclick-me` element, just on the `<span>`.

![listener-removed](https://cloud.githubusercontent.com/assets/49545/22819116/89aedcd4-ef25-11e6-98cf-703dab3e3311.gif)

Stopping event propagation in the `unclick` handler will also prevent the `click` handler from being re-triggered.

**Comment by tivac** [comment] 2017-02-10 08:26
Here's a smaller repro: https://jsbin.com/nesehey/3/edit?js,output

**Comment by pygy** [comment] 2017-02-10 08:52
Another argument for #1592

Conspiracy theory: I'm starting to think @lhorie is actually a secret Zalgo priest, luring unsuspecting coders to feed his master. The Zalgo article was mentioned in #1, and Leo is usually convinced by rational arguments, yet, maybe-sync redraws are still there, justified as an optimization, and calls for always async are ignored...

Sync redraws wins at best 16 ms, 8 on average on platforms that support rAF... Changes that happen within 100ms are percieved as instantaneous... Incorrect code is infinitely slower, anyway.

**Comment by ilsenem** [comment] 2017-02-10 09:04
https://codepen.io/ilsenem/pen/JEeYzx?editors=0010

This behavior is not the case in `v0.2.5` with the same code base.

It may be fast redraw as @tivac mentioned.

**Comment by isiahmeadows** [comment] 2017-02-11 12:41
@pygy 

> Conspiracy theory: I'm starting to think @lhorie is actually a secret Zalgo priest [...]

*He must've been teaming up with [this guy](http://stackoverflow.com/a/1732454) at one point!* :laughing: 

-----

In reality, I think it took the monster of 0.2 for him to start becoming a little more conservative when it comes to architecting the code. That old code base was almost the epitome of Zalgo. There was enough spaghetti logic to make improvement nearly impossible without breaking *everything*, over and over and over. (And this is why it wound up with a full revert - it was a read-only code base, where only the slightest change in seemingly unrelated areas caused an entire mountain to topple.)

**Comment by isiahmeadows** [comment] 2017-02-11 12:42
As for the current rewrite, I just haven't had the chance to take a decent look at it for performance tweaks.

**Comment by barneycarroll** [comment] 2017-02-21 15:12
@isiahmeadows this particular variant of Zalgo results from a consumer API contract that occasionally deviates from otherwise predictable resolution expectations - specifically: [mostly asynchronous but *sometimes synchronous*](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony). Like the unreliable attempt by `m.request` to delay redraw until all derivative `then`s have resolved, the 'occasionally sync' redraw is a whimsical feature with no use case, no documentation, and the potential to create incredibly confusing and difficult to debug expectation shortfalls.

**Comment by pygy** [comment] 2017-02-21 15:31
I'd say that here, Mithril unleashes Zalgo on itself by calling said public API in the event handler...

A cheap "fix" would be to `setTimeout(m.redraw)` in the event handler wrapper...

**Comment by v4n** [comment] 2017-02-21 17:51
@pygy based on your early comment, I'm assuming https://github.com/lhorie/mithril.js/pull/1592 would fix this bug?

@isiahmeadows @tivac mind adding a bug label to this if you guys agree it's?

**Comment by pygy** [comment] 2017-02-21 18:32
@v4n it would, but I'd rather have #1643 merged first. Both PRs modify the tests in a way that causes conflicts and #1592 will be easier to rework than #1643. Adding a node there...

**Comment by pygy** [comment] 2017-02-21 20:56
@v4n if this is blocking you, you can add 

```JS
e.redraw = false
setTimeout(m.redraw)
```

to the problematic handlers

Live: https://codepen.io/anon/pen/EZqrMQ?editors=0010

**Comment by isiahmeadows** [comment] 2017-03-27 17:08
Found the culprit: [this branch should have an `else`](https://github.com/lhorie/mithril.js/blob/next/render/render.js#L570-L573).

**Comment by pygy** [comment] 2017-03-27 17:11
@isiahmeadows isn't covered [here](https://github.com/lhorie/mithril.js/blob/f272e36de02714c1b3e16351f7c31b75f08eab30/render/render.js#L489)?

**Comment by isiahmeadows** [comment] 2017-03-27 17:14
No, but my initial suspicion is wrong.

**Comment by isiahmeadows** [comment] 2017-03-27 17:14
The problem is that the *inexistence* isn't being handled correctly.

**Comment by isiahmeadows** [comment] 2017-03-27 17:15
Another suspect: [this function](https://github.com/lhorie/mithril.js/blob/f272e36de02714c1b3e16351f7c31b75f08eab30/render/render.js#L463-L467) should clean up removed attributes as well.

**Comment by isiahmeadows** [comment] 2017-03-27 17:17
It's not a 1.1 blocker, though (although it still repros).

**Comment by isiahmeadows** [comment] 2017-06-15 08:30
Closing in favor of #1804.

**Closed by isiahmeadows** 2017-06-15 08:30 UTC
Labels: bug
