### ISSUE TITLE
https://unpkg.com/mithril-stream is missing with 404

### ISSUE THREAD

**Issue by iaddict** [MithrilJS/mithril.js#2344] opened 2018-12-19 19:51 UTC
### Mithril Version: 1.0.0

https://unpkg.com/mithril-stream is not available anymore.

## Expected Behavior

unpkg responds with the mithril-stream library.

## Current Behavior

When trying to access the stream library at https://unpkg.com/mithril-stream a 404 response is returned.

**Comment by fuzetsu** [comment] 2018-12-19 21:14
I'm fairly certain this is an issue with unpkg.com, they are ignoring the main module name in the package.json of the project and redirecting to index.js for all packages.

You can follow the issue here: https://github.com/unpkg/unpkg.com/issues/156

**Comment by fuzetsu** [comment] 2018-12-19 21:18
That said, the mithril-stream npm package may be out of date, hasn't been updated for over a year.
https://www.npmjs.com/package/mithril-stream

The docs recommend using this package: 
https://github.com/MithrilJS/mithril.js/blob/next/docs/stream.md#description

I usually fetch it like this: https://unpkg.com/mithril@next/stream/stream.js

**Comment by isiahmeadows** [comment] 2018-12-20 03:14
Closing, since that's unpkg's problem, not ours. (You can always host the script on your own servers - it's pretty easy to do.)

**Closed by isiahmeadows** 2018-12-20 03:14 UTC

**Comment by iaddict** [comment] 2018-12-20 11:07
@isiahmeadows Well, maybe at least the documentation should be changed then.
See https://github.com/MithrilJS/mithril.js/blob/master/docs/stream.md

It stopped working yesterday by the way. I now host the file myself.

**Comment by isiahmeadows** [comment] 2018-12-20 23:01
@iaddict BTW, [it should be working again](https://github.com/unpkg/unpkg.com/issues/156#issuecomment-449162442). But as it stands, unpkg issues aren't generally things we can do anything about on our end, and best practice in general (for any framework or library, not just Mithril) is that if you need guarantees about availability, host it on servers you control rather than relying on a public CDN to host it for you.

**Comment by fuzetsu** [comment] 2018-12-20 23:44
@isiahmeadows You may have missed my earlier comment, or misunderstood it or @iaddict 's. 
The issue we're discussing is the `mithril-stream` npm package, it being out of date, and if the docs should continue recommending it if it's not being kept up to date.
> That said, the mithril-stream npm package may be out of date, hasn't been updated for over a year.
https://www.npmjs.com/package/mithril-stream
The docs recommend using the mithril-stream package:
https://github.com/MithrilJS/mithril.js/blob/next/docs/stream.md#description

**Comment by fuzetsu** [comment] 2018-12-20 23:52
New issue I guess?

**Comment by isiahmeadows** [comment] 2018-12-22 04:58
@fuzetsu File a new issue - that hasn't been republished in quite a while. It probably wouldn't be a terrible idea to have those updated as well, but this issue was about unpkg returning erroneous 404s and wrong files (I reproduced their issue with https://unpkg.com/mithril as well), not an outdated bundle.
